package com.mystaria.phantasmon.client.hub;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Comparator;
import java.util.List;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * D-34 — the Global Hub's build read from each format. The fixtures (generated by the backend's
 * {@code scripts/generate_hub_schematics.py}) hold the same 3×2×4 room: stone, oak planks, oak stairs facing east and
 * a block no client knows; the Litematica one has a negative x size.
 */
class HubSchematicTest {

	private static HubSchematic read(String fixture) throws Exception {
		return HubSchematic.read(Files.readAllBytes(Path.of("src/test/resources/schematics", fixture)), fixture.endsWith(".litematic"));
	}

	private static void assertRoom(HubSchematic schematic) {
		assertEquals(3, schematic.sizeX());
		assertEquals(2, schematic.sizeY());
		assertEquals(4, schematic.sizeZ());
		List<HubSchematic.Block> blocks = schematic.blocks().stream()
				.sorted(Comparator.comparingInt(HubSchematic.Block::y).thenComparingInt(HubSchematic.Block::z)
						.thenComparingInt(HubSchematic.Block::x))
				.toList();
		assertEquals(4, blocks.size());
		assertBlock(blocks.get(0), 0, 0, 0, "minecraft:stone");
		assertBlock(blocks.get(1), 2, 0, 3, "minecraft:oak_planks");
		assertBlock(blocks.get(2), 1, 1, 2, "minecraft:oak_stairs");
		assertEquals("east", blocks.get(2).state().getCompound("Properties").getString("facing"));
		assertEquals("bottom", blocks.get(2).state().getCompound("Properties").getString("half"));
		assertBlock(blocks.get(3), 0, 1, 3, "phantasmon:unknown_block");
	}

	private static void assertBlock(HubSchematic.Block block, int x, int y, int z, String name) {
		assertArrayEquals(new int[] { x, y, z }, new int[] { block.x(), block.y(), block.z() }, name);
		assertEquals(name, block.name());
	}

	@Test
	void readsSpongeVersion2() throws Exception {
		assertRoom(read("room_v2.schem"));
	}

	@Test
	void readsSpongeVersion3() throws Exception {
		assertRoom(read("room_v3.schem"));
	}

	@Test
	void readsLitematicaWithANegativeRegionSize() throws Exception {
		assertRoom(read("room.litematic"));
	}

	@Test
	void parsesSpongeStateStrings() {
		var tag = HubSchematic.stateTag("oak_door[facing=south,half=upper]");
		assertEquals("minecraft:oak_door", tag.getString("Name"));
		assertEquals("upper", tag.getCompound("Properties").getString("half"));
		assertEquals(false, HubSchematic.stateTag("cobblemon:pc").contains("Properties"));
	}

	@Test
	void theBuildIsCentredOnTheAnchorsBlockAndTurnsWithIt() {
		HubBuildLayout south = HubBuildLayout.of(100.7, 64.0, -20.2, 0, 21, 21, 21);
		assertArrayEquals(new int[] { 100, 64, -21 }, south.toWorld(10, 0, 10));
		assertArrayEquals(new int[] { 90, 64, -31 }, south.min());
		assertArrayEquals(new int[] { 110, 84, -11 }, south.max());
		// The schematic's +Z (one block "ahead") follows the anchor's yaw: south, west, north, east.
		assertArrayEquals(new int[] { 100, 65, -20 }, south.toWorld(10, 1, 11));
		assertArrayEquals(new int[] { 99, 65, -21 }, HubBuildLayout.of(100.7, 64.0, -20.2, 90, 21, 21, 21).toWorld(10, 1, 11));
		assertArrayEquals(new int[] { 100, 65, -22 }, HubBuildLayout.of(100.7, 64.0, -20.2, 180, 21, 21, 21).toWorld(10, 1, 11));
		assertArrayEquals(new int[] { 101, 65, -21 }, HubBuildLayout.of(100.7, 64.0, -20.2, -90, 21, 21, 21).toWorld(10, 1, 11));
		// D-35: 3 wide, 15 long; facing west the length runs along x.
		HubBuildLayout corridor = HubBuildLayout.of(0.5, 64.0, 0.5, 90, 3, 3, 15);
		assertArrayEquals(new int[] { -7, 64, -1 }, corridor.min());
		assertArrayEquals(new int[] { 7, 66, 1 }, corridor.max());
		// A player standing on a slab: the build starts on the next block.
		assertEquals(65, HubBuildLayout.of(0, 64.5, 0, 0, 21, 21, 21).baseY());
	}
}
