package com.mystaria.phantasmon.client.gui;

import java.util.List;
import java.util.Locale;
import java.util.Map;

import com.cobblemon.mod.common.api.abilities.Abilities;
import com.cobblemon.mod.common.api.abilities.AbilityTemplate;
import com.cobblemon.mod.common.api.moves.MoveTemplate;
import com.cobblemon.mod.common.api.moves.Moves;
import com.cobblemon.mod.common.api.pokemon.PokemonSpecies;
import com.cobblemon.mod.common.api.types.ElementalType;
import com.cobblemon.mod.common.api.types.ElementalTypes;
import com.cobblemon.mod.common.pokemon.FormData;
import com.cobblemon.mod.common.pokemon.Species;
import com.mojang.blaze3d.systems.RenderSystem;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.math.Axis;

import net.minecraft.ChatFormatting;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.MutableComponent;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.FormattedCharSequence;
import net.minecraft.world.item.ItemStack;

import com.mystaria.phantasmon.client.network.BackendErrorMessages;
import com.mystaria.phantasmon.client.pokemon.NatureModifiers;
import com.mystaria.phantasmon.client.pokemon.PokemonDto;
import com.mystaria.phantasmon.client.pokemon.PokemonGender;
import com.mystaria.phantasmon.client.trade.LiveTradeController;
import com.mystaria.phantasmon.client.trade.LiveTradeState;

/**
 * Live trade screen (Adrien 2026-10-02), a faithful port of the handoff
 * mock-up {@code phantasmon_trade_ui.html} / {@code SPEC_ECRAN_ECHANGE.md}.
 *
 * <p><b>Coordinates</b>: everything is laid out directly in the mock-up's own
 * 1600×900 px space — every number below is the spec's "px" column (zones
 * Z01-Z29) used verbatim. The canvas is then drawn through one pose scale of
 * {@code s/2} GUI units per px, with {@code s = min(1, width/800, height/450)}
 * (spec §2): at 1080p / GUI scale 2 one mock-up px is exactly one screen pixel,
 * so the zones line up with the reference capture; at any other scale the
 * canvas shrinks uniformly and stays centered. Mouse positions are converted
 * back with {@link #toCanvasX}/{@link #toCanvasY} before any hit test.
 *
 * <p><b>Text</b>: Minecraft's font only stays crisp at integer scales, so the
 * mock-up's 16px titles use scale 2 (one font pixel = 2 px) and every smaller
 * size scale 1 (spec §9: "privilégier les échelles 1 et 0,5" in GUI units).
 *
 * <p><b>Draw order</b>: in 1.21.1 {@code fill}/{@code drawString} are batched
 * while {@code blit} draws immediately, so a texture blitted after a fill
 * would end up <em>under</em> it (the same pipeline surprise documented for
 * the PC screen's drop-down). {@link #blitTexture} therefore always
 * {@code flush()}es first, which keeps the code order the visual order.
 * Modal windows are drawn at z=2000, above item icons and 3D models.
 *
 * <p>Gradients/halos the vanilla GUI can't draw are the PNGs generated by
 * {@code scripts/generate_trade_textures.py} from the mock-up's exact CSS.
 * Every state shown here is the server's ({@link LiveTradeState}) — clicks
 * only send requests through {@link LiveTradeController}.
 */
public final class PhantasmonTradeScreen extends Screen {

	private static final int CANVAS_W = 1600;
	private static final int CANVAS_H = 900;
	/** Z26 = Z12 + 586 px, Z27 = Z05 + 1376 px (spec §3 "Règles de répétition"). */
	private static final int RIGHT_CARD_OFFSET = 586;
	private static final int RIGHT_RAIL_OFFSET = 1376;

	// ---- Textures (scripts/generate_trade_textures.py) ----
	private static final Texture TEX_BACKGROUND = new Texture("background", 400, 225);
	private static final Texture TEX_RAIL = new Texture("rail", 97, 379);
	private static final Texture TEX_CARD = new Texture("card", 288, 379);
	private static final Texture TEX_HEAD_LEFT = new Texture("player_head_left", 344, 24);
	private static final Texture TEX_HEAD_RIGHT = new Texture("player_head_right", 344, 24);
	private static final Texture TEX_VIEWPORT = new Texture("viewport", 575, 235);
	private static final Texture TEX_MODAL = new Texture("modal", 260, 133);
	private static final Texture TEX_SHADOW = new Texture("shadow", 64, 16);
	private static final ResourceLocation SPRITE_STAR = ResourceLocation.fromNamespaceAndPath("phantasmon", "pc/star");

	// ---- Colors (spec §4, ARGB) ----
	private static final int CYAN = 0xFF50E6FF;
	private static final int CYAN2 = 0xFF2FB7C9;
	private static final int WHITE = 0xFFFFFFFF;
	private static final int MUTED = 0xFF9FD9E6;
	private static final int DIM = 0xFF999999;
	private static final int TITLE = 0xFF5FE6F2;
	private static final int TEXT2 = 0xFFCCCCCC;
	private static final int IV_COLOR = 0xFF88CCFF;
	private static final int EV_COLOR = 0xFFFFCC88;
	private static final int STAT_HEAD = 0xFF6C8C96;
	private static final int SLOT_TOP = 0xFFCBEAF0;
	private static final int MALE = 0xFF50BFFF;
	private static final int FEMALE = 0xFFFF7594;
	private static final int STAR = 0xFFFFDD33;
	private static final int ACCENT_LEFT = 0xFF50BFFF;
	private static final int ACCENT_RIGHT = 0xFFFF6688;
	private static final int READY_BORDER = 0xFF76FFB0;
	private static final int READY_TEXT = 0xFFBAFFD2;
	private static final int DANGER_BORDER = 0xFFFF5078;
	private static final int ERROR_TEXT = 0xFFFFAA66;

	private static final int PANEL_FILL = 0x69081422;
	private static final int PANEL_BORDER = 0xBF50E6FF;
	private static final int PANEL_INNER = 0x1F50E6FF;
	private static final int RAIL_BORDER = 0x7A50E6FF;
	private static final int LINE_12 = 0x1F50E6FF;
	private static final int LINE_20 = 0x3350E6FF;
	private static final int LINE_25 = 0x4050E6FF;
	private static final int LINE_28 = 0x4750E6FF;
	private static final int LINE_30 = 0x4D50E6FF;
	private static final int RAIL_FOOT_BG = 0x33000000;
	private static final int CARD_HEAD_BG = 0x6B02080F;
	private static final int INFO_BOX_BG = 0x6100080F;
	private static final int MOVE_BG = 0xFF07131F;
	private static final int STAT_EVEN_BG = 0x08FFFFFF;
	private static final int FOOTER_BG = 0xD1030A14;
	private static final int SLOT_BG = 0x820E3C4E;
	private static final int SLOT_BORDER = 0x5950E6FF;
	private static final int SLOT_HOVER_BG = 0x5950E6FF;
	private static final int SLOT_SELECTED_BG = 0x7350E6FF;
	private static final int VEIL = 0xD100050A;
	private static final int BAND_LABEL_BG = 0xFF081422;
	private static final int BADGE_BORDER = 0x54000000;

	private static final int[] STD_BUTTON = { 0xFF18466B, 0xFF0D2A42 };
	private static final int[] STD_BUTTON_HOVER = { 0xFF205C8D, 0xFF123859 };
	private static final int[] DANGER_BUTTON = { 0xFF6B182A, 0xFF420D18 };
	private static final int[] DANGER_BUTTON_HOVER = { 0xFF8D2038, 0xFF591222 };

	/** The whole canvas is drawn at 80% of the spec's size (Adrien 2026-10-02: full-screen was too big), still centered. */
	private static final float MENU_SCALE = 0.8f;
	/** Text scale of the card's values (item, nature, ability, moves, IV/EV) — scale 1 was too small to read (Adrien 2026-10-02). */
	private static final float VALUE_SCALE = 2f;
	private static final int NATURE_UP = 0xFFFF8A80;
	private static final int NATURE_DOWN = 0xFF80B4FF;

	// ---- 3D model tuning (same mechanism as the PC screen; not measurable outside the game) ----
	/** Outer pose scale of a rail slot's model, in canvas px space (×1.5 after Adrien's first test). */
	private static final float SLOT_MODEL_SCALE = 5.5f * 1.5f;
	/** Outer pose scale of a card's model (Z15), in canvas px space (size confirmed OK by Adrien). */
	private static final float CARD_MODEL_SCALE = 19f;
	/**
	 * The model hangs below its anchor: its visual center sits about
	 * {@code MODEL_CENTER_K × outerScale} px under it (value implied by the PC
	 * screen's tuned ratio). The anchor is derived from the box center with it,
	 * so the model stays centered when its scale changes.
	 */
	private static final float MODEL_CENTER_K = 7.9f;
	/**
	 * Extra downward shift in canvas px — models were drawn too high on the
	 * first test (Adrien 2026-10-02). Temporarily adjustable live with
	 * {@code /phantasmon debug tradeoffset slot|card <px>} (same approach as the
	 * PC's former {@code iconanchor} command), to be frozen here once tuned.
	 */
	private static volatile float slotModelOffset = 20f;
	private static volatile float cardModelOffset = 40f;

	// ---- Animations (spec §8) ----
	private static final float FLOAT_PERIOD_MS = 3500f;
	private static final float BALL_PERIOD_MS = 1800f;
	private static final float MODAL_FADE_MS = 200f;
	/** After a successful trade: the ball travels for 2 cycles, then "ÉCHANGE TERMINÉ" shows and the screen closes on its own (it used to loop forever). */
	private static final long TRANSFER_ANIMATION_MS = (long) (BALL_PERIOD_MS * 2);
	private static final long AUTO_CLOSE_MS = TRANSFER_ANIMATION_MS + 1800;

	private static final String[] STAT_KEYS = { "hp", "atk", "def", "spa", "spd", "spe" };

	private final LiveTradeController controller;
	private final long openedAt = System.currentTimeMillis();

	private float scale;
	private float originX;
	private float originY;
	private boolean quitConfirmOpen;
	private long completedAt = -1;

	public PhantasmonTradeScreen(LiveTradeController controller) {
		super(Component.translatable("phantasmon.trade.screen.title"));
		this.controller = controller;
	}

	@Override
	protected void init() {
		float s = Math.min(1f, Math.min(this.width / 800f, this.height / 450f));
		scale = s / 2f * MENU_SCALE;
		originX = (this.width - CANVAS_W * scale) / 2f;
		originY = (this.height - CANVAS_H * scale) / 2f;
	}

	/** Debug hook for {@code /phantasmon debug tradeoffset} — see {@link #slotModelOffset}. */
	public static void setModelOffset(boolean card, float px) {
		if (card) {
			cardModelOffset = px;
		} else {
			slotModelOffset = px;
		}
	}

	public static float modelOffset(boolean card) {
		return card ? cardModelOffset : slotModelOffset;
	}

	@Override
	public boolean isPauseScreen() {
		return false;
	}

	@Override
	public boolean shouldCloseOnEsc() {
		return false;
	}

	@Override
	public void tick() {
		LiveTradeState state = controller.state();
		if (state == null || state.phase() == LiveTradeState.Phase.CANCELLED) {
			onClose();
		} else if (completedAt > 0 && System.currentTimeMillis() - completedAt >= AUTO_CLOSE_MS) {
			controller.closeAfterCompletion();
		}
	}

	@Override
	public void removed() {
		controller.onScreenRemoved();
	}

	// =====================================================================
	// Input
	// =====================================================================

	@Override
	public boolean mouseClicked(double mouseX, double mouseY, int button) {
		LiveTradeState state = controller.state();
		if (button != 0 || state == null) {
			return super.mouseClicked(mouseX, mouseY, button);
		}
		double x = toCanvasX(mouseX);
		double y = toCanvasY(mouseY);

		if (state.phase() == LiveTradeState.Phase.COMPLETED) {
			if (inside(x, y, 753, 529, 94, 28)) {
				controller.closeAfterCompletion();
			}
			return true;
		}
		if (quitConfirmOpen) {
			if (inside(x, y, 695, 476, 103, 28)) {
				quitConfirmOpen = false;
			} else if (inside(x, y, 808, 476, 97, 28)) {
				controller.leave();
				onClose();
			}
			return true;
		}
		if (inside(x, y, 715, 15, 170, 48)) {
			controller.toggleReady();
			return true;
		}
		if (inside(x, y, 1475, 849, 97, 28)) {
			quitConfirmOpen = true;
			return true;
		}
		int slot = slotAt(x, y, 0);
		if (slot >= 0) {
			controller.selectOffer(state.ownSlot(slot));
			return true;
		}
		// Right rail: read-only, the partner's offer is driven by the server (Adrien 2026-10-02).
		return true;
	}

	@Override
	public boolean keyPressed(int keyCode, int scanCode, int modifiers) {
		if (keyCode == 256) {
			LiveTradeState state = controller.state();
			if (state != null && state.phase() == LiveTradeState.Phase.COMPLETED) {
				controller.closeAfterCompletion();
			} else {
				// Échap = same as QUITTER (spec §7.4): opens the confirmation, or closes it again.
				quitConfirmOpen = !quitConfirmOpen;
			}
			return true;
		}
		return super.keyPressed(keyCode, scanCode, modifiers);
	}

	/** Rail slot index under (x, y) for the rail starting at Z05 + {@code railOffset}, -1 if none (spec §3: 2×3 grid, 85×214 slots, 92/221 px steps). */
	private static int slotAt(double x, double y, int railOffset) {
		for (int i = 0; i < LiveTradeState.TEAM_SIZE; i++) {
			if (inside(x, y, slotX(i) + railOffset, slotY(i), 85, 214)) {
				return i;
			}
		}
		return -1;
	}

	private static int slotX(int index) {
		return 24 + (index % 2) * 92;
	}

	private static int slotY(int index) {
		return 117 + (index / 2) * 221;
	}

	private double toCanvasX(double guiX) {
		return (guiX - originX) / scale;
	}

	private double toCanvasY(double guiY) {
		return (guiY - originY) / scale;
	}

	private static boolean inside(double x, double y, int bx, int by, int bw, int bh) {
		return x >= bx && x < bx + bw && y >= by && y < by + bh;
	}

	// =====================================================================
	// Rendering
	// =====================================================================

	@Override
	public void renderBackground(GuiGraphics graphics, int mouseX, int mouseY, float partialTick) {
		// Drawn explicitly at the start of render() — a no-op here so nothing ever draws it twice.
	}

	@Override
	public void render(GuiGraphics graphics, int mouseX, int mouseY, float partialTick) {
		LiveTradeState state = controller.state();
		// Now that the menu no longer fills the screen, the (blurred, dimmed) game shows around it.
		super.renderBackground(graphics, mouseX, mouseY, partialTick);
		if (state == null) {
			return;
		}
		if (state.phase() == LiveTradeState.Phase.COMPLETED && completedAt < 0) {
			completedAt = System.currentTimeMillis();
			quitConfirmOpen = false;
		}
		boolean modalOpen = quitConfirmOpen || state.phase() == LiveTradeState.Phase.COMPLETED;
		double mx = modalOpen ? -1 : toCanvasX(mouseX);
		double my = modalOpen ? -1 : toCanvasY(mouseY);

		PoseStack pose = graphics.pose();
		pose.pushPose();
		pose.translate(originX, originY, 0);
		pose.scale(scale, scale, 1f);

		renderRootPanel(graphics);
		renderHeader(graphics, state, mx, my);
		renderRail(graphics, state, 0, mx, my);
		renderRail(graphics, state, RIGHT_RAIL_OFFSET, mx, my);
		renderCard(graphics, state, 0);
		renderCard(graphics, state, RIGHT_CARD_OFFSET);
		renderFooter(graphics, state, mx, my);
		pose.popPose();

		if (state.phase() == LiveTradeState.Phase.COMPLETED) {
			renderTradeModal(graphics, state, mouseX, mouseY);
		} else if (quitConfirmOpen) {
			renderQuitModal(graphics, mouseX, mouseY);
		}
	}

	/** Z01: translucent fill, 2 px cyan border + 1 px inner line, the two neon bars across the top edge. */
	private void renderRootPanel(GuiGraphics g) {
		blitTexture(g, TEX_BACKGROUND, 0, 0, CANVAS_W, CANVAS_H);
		g.fill(0, 0, CANVAS_W, CANVAS_H, PANEL_FILL);
		g.fill(0, 0, CANVAS_W, 2, PANEL_BORDER);
		g.fill(0, CANVAS_H - 2, CANVAS_W, CANVAS_H, PANEL_BORDER);
		g.fill(0, 2, 2, CANVAS_H - 2, PANEL_BORDER);
		g.fill(CANVAS_W - 2, 2, CANVAS_W, CANVAS_H - 2, PANEL_BORDER);
		g.renderOutline(2, 2, CANVAS_W - 4, CANVAS_H - 4, PANEL_INNER);
		int barWidth = Math.round(CANVAS_W * 0.34f);
		for (int barX : new int[] { 0, CANVAS_W - barWidth }) {
			g.fillGradient(barX, -15, barX + barWidth, -2, 0x0050E6FF, 0x5550E6FF);
			g.fill(barX, -2, barX + barWidth, 2, CYAN);
			g.fillGradient(barX, 2, barX + barWidth, 15, 0x5550E6FF, 0x0050E6FF);
		}
	}

	// ---- Z02 / Z03 / Z04 ----

	private void renderHeader(GuiGraphics g, LiveTradeState state, double mx, double my) {
		blitTexture(g, TEX_HEAD_LEFT, 15, 15, 688, 48);
		g.renderOutline(15, 15, 688, 48, CYAN2);
		blitTexture(g, TEX_HEAD_RIGHT, 897, 15, 688, 48);
		g.renderOutline(897, 15, 688, 48, CYAN2);

		String ownName = upper(controller.localPlayerName());
		drawText(g, ownName, 31, 32, 2f, WHITE, true, 1.5f);
		String partnerName = upper(state.partnerName());
		float partnerWidth = textWidth(partnerName, 2f, true, 1.5f);
		drawText(g, partnerName, 1569 - partnerWidth, 32, 2f, WHITE, true, 1.5f);
		if (state.partnerReady()) {
			// Not in the mock-up (which simulates the partner), but a real trade needs to show it.
			String ready = Component.translatable("phantasmon.trade.screen.ready").getString();
			drawText(g, ready, 1569 - partnerWidth - 16 - textWidth(ready, 1f, true, 2f), 36, 1f, READY_TEXT, true, 2f);
		}

		renderTradeButton(g, state, inside(mx, my, 715, 15, 170, 48));
	}

	/** Z03 — repos / survol / « PRÊT ✓ » (spec §4 Boutons, §7.3). */
	private void renderTradeButton(GuiGraphics g, LiveTradeState state, boolean hovered) {
		int x = 715;
		int y = 15;
		int w = 170;
		int h = 48;
		boolean ready = state.ownReady();
		int[] gradient = hovered ? STD_BUTTON_HOVER : STD_BUTTON;
		glowOutside(g, x, y, w, h, ready ? 0x76FFB0 : 0x50E6FF, ready ? 0.3f : 0.18f, 8);
		g.fillGradient(x, y, x + w, y + h, gradient[0], gradient[1]);
		g.renderOutline(x, y, w, h, ready ? READY_BORDER : CYAN);
		if (ready) {
			String label = Component.translatable("phantasmon.trade.screen.ready").getString();
			float width = textWidth(label, 2f, true, 1f);
			drawText(g, label, x + (w - width) / 2f, y + 17, 2f, READY_TEXT, true, 1f);
		} else {
			String arrows = "⇄";
			String label = upper(Component.translatable("phantasmon.trade.screen.trade_button").getString());
			float arrowsWidth = textWidth(arrows, 2f, false, 0f);
			float labelScale = textWidth(label, 2f, true, 1f) + arrowsWidth + 6 <= w - 12 ? 2f : 1f;
			float labelWidth = textWidth(label, labelScale, true, 1f);
			float startX = x + (w - arrowsWidth - 6 - labelWidth) / 2f;
			drawText(g, arrows, startX, y + 16, 2f, CYAN, false, 0f);
			drawText(g, label, startX + arrowsWidth + 6, y + (h - 7 * labelScale) / 2f, labelScale, CYAN, true, 1f);
		}
	}

	// ---- Z05-Z11 / Z27 ----

	private void renderRail(GuiGraphics g, LiveTradeState state, int dx, double mx, double my) {
		boolean own = dx == 0;
		blitTexture(g, TEX_RAIL, 15 + dx, 72, 194, 758);
		g.renderOutline(15 + dx, 72, 194, 758, RAIL_BORDER);

		String owner = own ? controller.localPlayerName() : state.partnerName();
		String title = upper(Component.translatable("phantasmon.trade.screen.team", owner).getString());
		drawText(g, fitText(title, 172, 1f, false, 2f), 28 + dx, 89, 1f, MUTED, false, 2f);
		g.fill(24 + dx, 108, 200 + dx, 109, LINE_25);

		int selected = own ? state.ownOfferIndex() : state.partnerOfferIndex();
		int hovered = own ? slotAt(mx, my, 0) : -1;
		for (int i = 0; i < LiveTradeState.TEAM_SIZE; i++) {
			PokemonDto pokemon = own ? state.ownSlot(i) : state.partnerSlot(i);
			SlotLook look = i == selected ? SlotLook.SELECTED : (i == hovered && pokemon != null ? SlotLook.HOVER : SlotLook.NORMAL);
			renderSlot(g, slotX(i) + dx, slotY(i), pokemon, look);
		}

		g.fill(24 + dx, 781, 200 + dx, 821, RAIL_FOOT_BG);
		g.renderOutline(24 + dx, 781, 176, 40, LINE_25);
		Component hint = own ? Component.translatable("phantasmon.trade.screen.rail_hint_own")
				: Component.translatable("phantasmon.trade.screen.rail_hint_partner", state.partnerName());
		List<FormattedCharSequence> lines = font.split(hint, 162);
		int lineCount = Math.min(2, lines.size());
		float lineY = 781 + (40 - lineCount * 12) / 2f + 2;
		for (int i = 0; i < lineCount; i++) {
			int width = font.width(lines.get(i));
			drawSequence(g, lines.get(i), 24 + dx + (176 - width) / 2f, lineY + i * 12, DIM);
		}
	}

	private enum SlotLook { NORMAL, HOVER, SELECTED }

	/** Z08: gender + level on top, model (Z09), name, held item (Z10). Empty slots keep the normal look (spec §6.2). */
	private void renderSlot(GuiGraphics g, int x, int y, PokemonDto pokemon, SlotLook look) {
		int w = 85;
		int h = 214;
		switch (look) {
			case SELECTED -> {
				g.fill(x, y, x + w, y + h, SLOT_SELECTED_BG);
				glowInside(g, x, y, w, h, 0x50E6FF, 0.35f, 7);
				g.renderOutline(x, y, w, h, WHITE);
			}
			case HOVER -> {
				g.fill(x, y, x + w, y + h, SLOT_HOVER_BG);
				g.renderOutline(x, y, w, h, CYAN);
			}
			default -> {
				g.fill(x, y, x + w, y + h, SLOT_BG);
				g.renderOutline(x, y, w, h, SLOT_BORDER);
			}
		}
		if (pokemon == null) {
			return;
		}
		Look info = Look.of(pokemon);

		drawGender(g, info.gender(), x + 6, y + 6, 1f);
		String level = Component.translatable("phantasmon.trade.screen.level_short", pokemon.level()).getString();
		drawText(g, level, x + 79 - textWidth(level, 1f, false, 0f), y + 6, 1f, SLOT_TOP, false, 0f);

		// Model area = everything between the top labels and the name (models are ×1.5 bigger than the spec's 72 px icon).
		int modelTop = y + 18;
		int modelHeight = 142;
		g.flush();
		enableCanvasScissor(g, x + 1, modelTop, w - 2, modelHeight);
		PokemonGuiRendering.renderModel(g, pokemon.species(), pokemon.form(), pokemon.isShiny(),
				x + w / 2f, modelAnchorY(modelTop + modelHeight / 2f, SLOT_MODEL_SCALE, slotModelOffset), SLOT_MODEL_SCALE);
		g.disableScissor();

		String starPrefix = pokemon.isShiny() ? "★ " : "";
		String name = fitText(displayName(pokemon), 75 - textWidth(starPrefix, 1f, true, 0f), 1f, true, 0f);
		float starWidth = textWidth(starPrefix, 1f, true, 0f);
		float nameStart = x + (w - starWidth - textWidth(name, 1f, true, 0f)) / 2f;
		if (!starPrefix.isEmpty()) {
			drawText(g, starPrefix, nameStart, y + modelHeight + 22, 1f, STAR, true, 0f);
		}
		drawText(g, name, nameStart + starWidth, y + modelHeight + 22, 1f, WHITE, true, 0f);

		ItemStack item = heldItem(pokemon);
		if (!item.isEmpty()) {
			PokemonGuiRendering.renderItemIcon(g, item, x + 59, y + 188, 20);
		}
	}

	// ---- Z12-Z25 / Z26 ----

	private void renderCard(GuiGraphics g, LiveTradeState state, int dx) {
		boolean own = dx == 0;
		blitTexture(g, TEX_CARD, 219 + dx, 72, 577, 758);
		g.renderOutline(219 + dx, 72, 577, 758, CYAN2);
		g.fill(219 + dx, 72, 796 + dx, 75, own ? ACCENT_LEFT : ACCENT_RIGHT);

		PokemonDto pokemon = own ? state.ownOfferPokemon() : state.partnerOfferPokemon();
		String owner = own ? controller.localPlayerName() : state.partnerName();
		if (pokemon == null) {
			Component waiting = own
					? Component.translatable(state.firstOwnPokemon() == null ? "phantasmon.trade.screen.empty_team" : "phantasmon.trade.screen.waiting_own")
					: Component.translatable("phantasmon.trade.screen.waiting_offer", owner);
			String text = waiting.getString();
			drawText(g, text, 219 + dx + (577 - textWidth(text, 1f, false, 0f)) / 2f, 447, 1f, DIM, false, 0f);
			return;
		}
		Look info = Look.of(pokemon);
		renderCardHead(g, pokemon, info, owner, dx);
		renderViewport(g, pokemon, info, dx);
		renderInfo(g, pokemon, info, dx);
	}

	/** Anchor that puts the model's visual center on {@code boxCenterY} — see {@link #MODEL_CENTER_K}. */
	private static float modelAnchorY(float boxCenterY, float outerScale, float offset) {
		return boxCenterY - MODEL_CENTER_K * outerScale + offset;
	}

	/** Z13: name + gender left, owner centered between them (flex space-between), "Nv. X" right. */
	private void renderCardHead(GuiGraphics g, PokemonDto pokemon, Look info, String owner, int dx) {
		g.fill(220 + dx, 75, 795 + dx, 117, CARD_HEAD_BG);
		g.fill(220 + dx, 116, 795 + dx, 117, LINE_28);

		String level = Component.translatable("phantasmon.trade.screen.level", pokemon.level()).getString();
		float levelWidth = textWidth(level, 2f, true, 0f);
		float levelX = 784 + dx - levelWidth;
		String ownerText = upper(owner);
		float ownerWidth = textWidth(ownerText, 1f, false, 1.5f);

		float genderWidth = info.gender() == PokemonGender.MALE || info.gender() == PokemonGender.FEMALE ? 14 : 0;
		float nameMax = Math.max(40, (levelX - (231 + dx)) - ownerWidth - genderWidth - 24);
		String name = fitText(displayName(pokemon), nameMax, 2f, true, 0.6f);
		float nameWidth = textWidth(name, 2f, true, 0.6f);
		drawText(g, name, 231 + dx, 89, 2f, WHITE, true, 0.6f);
		drawGender(g, info.gender(), 231 + dx + nameWidth + 6, 93, 1f);

		float nameRight = 231 + dx + nameWidth + genderWidth;
		float ownerX = nameRight + (levelX - nameRight - ownerWidth) / 2f;
		drawText(g, ownerText, ownerX, 93, 1f, MUTED, false, 1.5f);
		drawText(g, level, levelX, 89, 2f, WHITE, true, 0f);
	}

	/** Z14-Z16: halo/grid background, type badges, shiny star, floating 3D model with its shadow. */
	private void renderViewport(GuiGraphics g, PokemonDto pokemon, Look info, int dx) {
		blitTexture(g, TEX_VIEWPORT, 220 + dx, 117, 575, 235);

		int badgeX = 229 + dx;
		for (ElementalType type : info.types()) {
			badgeX += drawTypeBadge(g, type, badgeX, 126) + 4;
		}
		if (pokemon.isShiny()) {
			g.flush();
			g.blitSprite(SPRITE_STAR, 795 + dx - 10 - 18, 125, 18, 18);
		}

		float t = (System.currentTimeMillis() - openedAt) % FLOAT_PERIOD_MS / FLOAT_PERIOD_MS;
		float ease = (1f - (float) Math.cos(t * 2 * Math.PI)) / 2f;
		blitTexture(g, TEX_SHADOW, 437 + dx, 318, 140, 26);

		g.flush();
		enableCanvasScissor(g, 220 + dx, 117, 575, 235);
		PoseStack pose = g.pose();
		pose.pushPose();
		float centerX = 220 + dx + 575 / 2f;
		float anchorY = modelAnchorY(117 + 235 / 2f, CARD_MODEL_SCALE, cardModelOffset);
		pose.translate(centerX, anchorY - 5f * ease, 0);
		float grow = 1f + 0.015f * ease;
		pose.scale(grow, grow, 1f);
		PokemonGuiRendering.renderModel(g, pokemon.species(), pokemon.form(), pokemon.isShiny(), 0, 0, CARD_MODEL_SCALE);
		pose.popPose();
		g.disableScissor();
	}

	/**
	 * Z17-Z25, enlarged after Adrien's first test (2026-10-02): every value is
	 * drawn at {@link #VALUE_SCALE} and the boxes are re-spread over the whole
	 * info block (the mock-up left ~180 px empty under moves and IV/EV). Each
	 * move also gets its type badge; the nature shows its +/- stats, mirrored
	 * by colored stat labels in the IV/EV box — no other additions.
	 */
	private void renderInfo(GuiGraphics g, PokemonDto pokemon, Look info, int dx) {
		g.fill(220 + dx, 352, 795 + dx, 353, LINE_20);
		Map<String, Object> data = pokemon.data() != null ? pokemon.data() : Map.of();

		// Z18 Objet tenu
		infoBox(g, 228 + dx, 361, 276, 56, "phantasmon.trade.screen.held_item");
		float valueY = 361 + 25;
		ItemStack item = heldItem(pokemon);
		String itemText;
		float valueX = 237 + dx;
		if (!item.isEmpty()) {
			PokemonGuiRendering.renderItemIcon(g, item, valueX, valueY - 3, 20);
			valueX += 26;
			itemText = item.getHoverName().getString();
		} else {
			Object raw = data.get("heldItem");
			itemText = raw != null && !raw.toString().isBlank() ? raw.toString()
					: Component.translatable("phantasmon.trade.screen.no_item").getString();
		}
		drawText(g, fitText(itemText, 504 + dx - 9 - valueX, VALUE_SCALE, false, 0f), valueX, valueY, VALUE_SCALE, WHITE, false, 0f);

		// Z19 Nature (+ its boosted/lowered stats, small, after the name)
		infoBox(g, 510 + dx, 361, 276, 56, "phantasmon.trade.screen.nature");
		NatureModifiers.Modifier modifier = NatureModifiers.get(pokemon.nature());
		String modifierText = modifier == null ? "" : "+" + modifier.boosted() + " / -" + modifier.reduced();
		float modifierWidth = textWidth(modifierText, 1f, false, 0f);
		String nature = fitText(NatureModifiers.displayName(pokemon.nature()), 258 - (modifierWidth > 0 ? modifierWidth + 8 : 0), VALUE_SCALE, false, 0f);
		drawText(g, nature, 519 + dx, valueY, VALUE_SCALE, WHITE, false, 0f);
		if (modifier != null) {
			drawText(g, modifierText, 777 + dx - modifierWidth, valueY + 4, 1f, MUTED, false, 0f);
		}

		// Z20 Talent, Z21 Téracristal
		infoBox(g, 228 + dx, 424, 276, 56, "phantasmon.trade.screen.ability");
		valueY = 424 + 25;
		drawText(g, fitText(abilityLabel(pokemon.ability()), 258, VALUE_SCALE, false, 0f), 237 + dx, valueY, VALUE_SCALE, WHITE, false, 0f);
		infoBox(g, 510 + dx, 424, 276, 56, "phantasmon.trade.screen.tera");
		if (info.teraType() != null) {
			drawTypeBadge(g, info.teraType(), 519 + dx, valueY - 3, VALUE_SCALE);
		}

		// Z22-Z23 Capacités: 4 tall rows, name left + type badge right, empty rows kept
		infoBox(g, 228 + dx, 488, 303, 333, "phantasmon.trade.screen.moves");
		List<Object> moves = asList(data.get("moves"));
		for (int i = 0; i < 4; i++) {
			int rowY = 512 + i * 76;
			int rowH = 68;
			g.fill(237 + dx, rowY, 522 + dx, rowY + rowH, MOVE_BG);
			g.renderOutline(237 + dx, rowY, 285, rowH, LINE_12);
			if (i >= moves.size()) {
				continue;
			}
			String moveId = moves.get(i).toString();
			MoveTemplate template = Moves.INSTANCE.getByName(moveId);
			float nameMax = 285 - 20;
			if (template != null && template.getElementalType() != null) {
				int badgeWidth = typeBadgeWidth(template.getElementalType(), 1f);
				drawTypeBadge(g, template.getElementalType(), 522 + dx - 10 - badgeWidth, rowY + (rowH - 19) / 2, 1f);
				nameMax -= badgeWidth + 8;
			}
			String move = fitText(template != null ? template.getDisplayName().getString() : moveId, nameMax, VALUE_SCALE, false, 0f);
			drawText(g, move, 247 + dx, rowY + (rowH - 7 * VALUE_SCALE) / 2f, VALUE_SCALE, TEXT2, false, 0f);
		}

		// Z24-Z25 IV / EV
		infoBox(g, 538 + dx, 488, 248, 333, "phantasmon.trade.screen.ivs_evs");
		int ivRight = 712 + dx;
		int evRight = 774 + dx;
		String ivHead = Component.translatable("phantasmon.trade.screen.iv").getString();
		String evHead = Component.translatable("phantasmon.trade.screen.ev").getString();
		drawText(g, ivHead, ivRight - textWidth(ivHead, 1f, true, 0f), 514, 1f, STAT_HEAD, true, 0f);
		drawText(g, evHead, evRight - textWidth(evHead, 1f, true, 0f), 514, 1f, STAT_HEAD, true, 0f);
		Map<String, Object> ivs = asMap(data.get("ivs"));
		Map<String, Object> evs = asMap(data.get("evs"));
		String boosted = modifier == null ? null : modifier.boosted().toLowerCase(Locale.ROOT);
		String reduced = modifier == null ? null : modifier.reduced().toLowerCase(Locale.ROOT);
		int rowH = 36;
		int evTotal = 0;
		for (int i = 0; i < STAT_KEYS.length; i++) {
			int rowY = 528 + i * rowH;
			if (i % 2 == 1) {
				g.fill(547 + dx, rowY, 777 + dx, rowY + rowH, STAT_EVEN_BG);
			}
			float textY = rowY + (rowH - 7 * VALUE_SCALE) / 2f;
			int labelColor = STAT_KEYS[i].equals(boosted) ? NATURE_UP : STAT_KEYS[i].equals(reduced) ? NATURE_DOWN : WHITE;
			String label = fitText(Component.translatable("phantasmon.trade.screen.stat." + STAT_KEYS[i]).getString(),
					ivRight - 36 - (551 + dx) - 8, VALUE_SCALE, false, 0f);
			drawText(g, label, 551 + dx, textY, VALUE_SCALE, labelColor, false, 0f);
			String iv = String.valueOf(asInt(ivs.get(STAT_KEYS[i])));
			int evValue = asInt(evs.get(STAT_KEYS[i]));
			evTotal += evValue;
			String ev = String.valueOf(evValue);
			drawText(g, iv, ivRight - textWidth(iv, VALUE_SCALE, false, 0f), textY, VALUE_SCALE, IV_COLOR, false, 0f);
			drawText(g, ev, evRight - textWidth(ev, VALUE_SCALE, false, 0f), textY, VALUE_SCALE, EV_COLOR, false, 0f);
		}
		int totalY = 528 + 6 * rowH + 6;
		g.fill(547 + dx, totalY, 777 + dx, totalY + 1, LINE_20);
		float totalTextY = totalY + 1 + (rowH - 7 * VALUE_SCALE) / 2f;
		drawText(g, Component.translatable("phantasmon.trade.screen.total_ev").getString(), 551 + dx, totalTextY, VALUE_SCALE, DIM, false, 0f);
		String total = String.valueOf(evTotal);
		drawText(g, total, evRight - textWidth(total, VALUE_SCALE, false, 0f), totalTextY, VALUE_SCALE, EV_COLOR, false, 0f);
	}

	private void infoBox(GuiGraphics g, int x, int y, int w, int h, String labelKey) {
		g.fill(x, y, x + w, y + h, INFO_BOX_BG);
		g.renderOutline(x, y, w, h, LINE_20);
		drawText(g, upper(Component.translatable(labelKey).getString()), x + 9, y + 8, 1f, TITLE, true, 1.2f);
	}

	// ---- Z28 / Z29 ----

	private void renderFooter(GuiGraphics g, LiveTradeState state, double mx, double my) {
		g.fill(15, 839, 1585, 886, FOOTER_BG);
		g.renderOutline(15, 839, 1570, 47, LINE_30);

		String status = statusLine(state);
		if (status != null) {
			drawText(g, fitText(status, 1420, 2f, false, 0f), 27, 855.5f, 2f,
					state.lastErrorCode() != null ? ERROR_TEXT : MUTED, false, 0f);
		}
		renderButton(g, 1475, 849, 97, 28, "phantasmon.trade.screen.quit", true, inside(mx, my, 1475, 849, 97, 28));
	}

	/** Left part of the footer — only when there's something to say (errors, or who we're waiting for). */
	private static String statusLine(LiveTradeState state) {
		if (state.lastErrorCode() != null) {
			return stripPrefix(Component.translatable(BackendErrorMessages.translationKey(state.lastErrorCode())).getString());
		}
		if (state.ownReady() && !state.partnerReady()) {
			return Component.translatable("phantasmon.trade.screen.waiting_partner", state.partnerName()).getString();
		}
		if (!state.ownReady() && state.partnerReady()) {
			return Component.translatable("phantasmon.trade.screen.partner_is_ready", state.partnerName()).getString();
		}
		return null;
	}

	private void renderButton(GuiGraphics g, int x, int y, int w, int h, String labelKey, boolean danger, boolean hovered) {
		int[] gradient = danger ? (hovered ? DANGER_BUTTON_HOVER : DANGER_BUTTON) : (hovered ? STD_BUTTON_HOVER : STD_BUTTON);
		g.fillGradient(x, y, x + w, y + h, gradient[0], gradient[1]);
		g.renderOutline(x, y, w, h, danger ? DANGER_BORDER : CYAN);
		String label = upper(Component.translatable(labelKey).getString());
		float width = textWidth(label, 1f, true, 1.5f);
		drawText(g, label, x + (w - width) / 2f, y + (h - 7) / 2f, 1f, WHITE, true, 1.5f);
	}

	// ---- Modals (spec §7.4 / §7.5) ----

	/** « ÉCHANGE EN COURS »: opens on the server's {@code TradeSessionCompleted} (spec §7.3 step 4). */
	private void renderTradeModal(GuiGraphics g, LiveTradeState state, int mouseX, int mouseY) {
		float fade = Math.min(1f, (System.currentTimeMillis() - completedAt) / MODAL_FADE_MS);
		beginModalLayer(g, fade);
		double mx = toCanvasX(mouseX);
		double my = toCanvasY(mouseY);

		// Ball travels for TRANSFER_ANIMATION_MS, then the window switches to its "done" state until tick() auto-closes it.
		boolean done = System.currentTimeMillis() - completedAt >= TRANSFER_ANIMATION_MS;
		renderModalCard(g, 540, 317, 520, 266, fade);
		String title = Component.translatable(done ? "phantasmon.trade.screen.done" : "phantasmon.trade.screen.in_progress").getString();
		drawCentered(g, upper(title), 800, 344, 2f, withAlpha(done ? READY_TEXT : TITLE, fade), true, 2f);

		// Transfer band: our name, the gradient line, the travelling Poké Ball, the partner's name.
		int bandX = 566;
		int bandY = 383;
		int bandW = 468;
		g.renderOutline(bandX, bandY, bandW, 90, withAlpha(LINE_30, fade));
		int lineY = bandY + 44;
		int lineStart = bandX + Math.round(bandW * 0.08f);
		int lineEnd = bandX + Math.round(bandW * 0.92f);
		g.fillGradient(lineStart, lineY - 8, lineEnd, lineY, 0x0050E6FF, withAlpha(0x4050E6FF, fade));
		g.fillGradient(lineStart, lineY + 3, lineEnd, lineY + 11, withAlpha(0x4050E6FF, fade), 0x0050E6FF);
		for (int x = lineStart; x < lineEnd; x++) {
			float t = (x - lineStart) / (float) (lineEnd - lineStart);
			int color = t < 0.5f ? lerpColor(0x50E6FF, 0xFFFFFF, t * 2) : lerpColor(0xFFFFFF, 0xFF5078, (t - 0.5f) * 2);
			g.fill(x, lineY, x + 1, lineY + 3, withAlpha(0xFF000000 | color, fade));
		}
		bandLabel(g, controller.localPlayerName(), bandX + 30, lineY, false, fade);
		bandLabel(g, state.partnerName(), bandX + bandW - 30, lineY, true, fade);
		if (!done) {
			renderPokeBall(g, bandX + bandW / 2f, lineY + 1.5f, fade);
		}

		PokemonDto given = state.givenPokemon();
		PokemonDto received = state.receivedPokemon();
		String text = Component.translatable(done ? "phantasmon.trade.screen.done_text" : "phantasmon.trade.screen.in_progress_text",
				given == null ? "?" : displayName(given), received == null ? "?" : displayName(received)).getString();
		float textScale = textWidth(text, 2f, false, 0f) <= 470 ? 2f : 1f;
		drawCentered(g, fitText(text, 470, textScale, false, 0f), 800, 497 - 3.5f * textScale, textScale, withAlpha(TEXT2, fade), false, 0f);

		renderButton(g, 753, 529, 94, 28, "phantasmon.trade.screen.close", false, inside(mx, my, 753, 529, 94, 28));
		endModalLayer(g);
	}

	/** « QUITTER L'ÉCHANGE ? » (spec §7.4, ref_04_quitter.png). */
	private void renderQuitModal(GuiGraphics g, int mouseX, int mouseY) {
		beginModalLayer(g, 1f);
		double mx = toCanvasX(mouseX);
		double my = toCanvasY(mouseY);
		renderModalCard(g, 540, 370, 520, 160, 1f);
		drawCentered(g, upper(Component.translatable("phantasmon.trade.screen.quit_title").getString()), 800, 397, 2f, TITLE, true, 2f);
		drawCentered(g, Component.translatable("phantasmon.trade.screen.quit_text").getString(), 800, 437, 2f, TEXT2, false, 0f);
		renderButton(g, 695, 476, 103, 28, "phantasmon.trade.screen.cancel", false, inside(mx, my, 695, 476, 103, 28));
		renderButton(g, 808, 476, 97, 28, "phantasmon.trade.screen.quit", true, inside(mx, my, 808, 476, 97, 28));
		endModalLayer(g);
	}

	/** Full-screen veil then the canvas transform again, all lifted to z=2000 (above item icons/3D models drawn underneath). */
	private void beginModalLayer(GuiGraphics g, float fade) {
		g.flush();
		PoseStack pose = g.pose();
		pose.pushPose();
		pose.translate(0, 0, 2000);
		g.fill(0, 0, this.width, this.height, withAlpha(VEIL, fade));
		pose.translate(originX, originY, 0);
		pose.scale(scale, scale, 1f);
	}

	private void endModalLayer(GuiGraphics g) {
		g.flush();
		g.pose().popPose();
	}

	private void renderModalCard(GuiGraphics g, int x, int y, int w, int h, float fade) {
		glowOutside(g, x, y, w, h, 0x50E6FF, 0.18f * fade, 14);
		// Flush first: the shader color tint must only apply to this one blit, not to the pending batch.
		g.flush();
		RenderSystem.setShaderColor(1f, 1f, 1f, fade);
		blitTexture(g, TEX_MODAL, x, y, w, h);
		RenderSystem.setShaderColor(1f, 1f, 1f, 1f);
		g.renderOutline(x, y, w, h, withAlpha(CYAN, fade));
	}

	private void bandLabel(GuiGraphics g, String name, float anchorX, int lineY, boolean rightAligned, float fade) {
		String label = fitText(upper(name), 150, 1f, true, 0f);
		float labelScale = textWidth(label, 2f, true, 0f) <= 150 ? 2f : 1f;
		float width = textWidth(label, labelScale, true, 0f);
		float x = rightAligned ? anchorX - width : anchorX;
		float y = lineY + 1.5f - 3.5f * labelScale;
		g.fill(Math.round(x - 6), Math.round(y - 3), Math.round(x + width + 6), Math.round(y + 7 * labelScale + 3), withAlpha(BAND_LABEL_BG, fade));
		drawText(g, label, x, y, labelScale, withAlpha(WHITE, fade), true, 0f);
	}

	/** Poké Ball going back and forth 180 px with a full turn, 1.8 s linear cycle (spec §8). */
	private void renderPokeBall(GuiGraphics g, float centerX, float centerY, float fade) {
		if (fade < 0.5f) {
			return;
		}
		ItemStack ball = new ItemStack(BuiltInRegistries.ITEM.get(ResourceLocation.fromNamespaceAndPath("cobblemon", "poke_ball")));
		if (ball.isEmpty()) {
			return;
		}
		float p = (System.currentTimeMillis() % (long) BALL_PERIOD_MS) / BALL_PERIOD_MS;
		float triangle = p < 0.5f ? p * 2f : (1f - p) * 2f;
		PoseStack pose = g.pose();
		pose.pushPose();
		pose.translate(centerX - 90 + 180 * triangle, centerY, 0);
		pose.mulPose(Axis.ZP.rotationDegrees(360f * triangle));
		pose.scale(28 / 16f, 28 / 16f, 1f);
		g.renderItem(ball, -8, -8);
		pose.popPose();
	}

	// =====================================================================
	// Drawing helpers (all in canvas px)
	// =====================================================================

	private record Texture(ResourceLocation location, int width, int height) {
		Texture(String name, int width, int height) {
			this(ResourceLocation.fromNamespaceAndPath("phantasmon", "textures/gui/trade/" + name + ".png"), width, height);
		}
	}

	/** Stretched blit with blending on — flushes the pending fill/text batch first so code order stays draw order (see class javadoc). */
	private static void blitTexture(GuiGraphics g, Texture texture, int x, int y, int w, int h) {
		g.flush();
		RenderSystem.enableBlend();
		RenderSystem.defaultBlendFunc();
		g.blit(texture.location(), x, y, w, h, 0f, 0f, texture.width(), texture.height(), texture.width(), texture.height());
		RenderSystem.disableBlend();
	}

	/** Approximates a CSS outer {@code box-shadow} glow with fading 1 px rings. */
	private static void glowOutside(GuiGraphics g, int x, int y, int w, int h, int rgb, float alpha, int size) {
		for (int i = 1; i <= size; i++) {
			float falloff = 1f - (i - 1) / (float) size;
			g.renderOutline(x - i, y - i, w + 2 * i, h + 2 * i, argb(rgb, alpha * falloff * falloff));
		}
	}

	/** Same for an {@code inset} glow (selected slot). */
	private static void glowInside(GuiGraphics g, int x, int y, int w, int h, int rgb, float alpha, int size) {
		for (int i = 1; i <= size; i++) {
			float falloff = 1f - (i - 1) / (float) size;
			g.renderOutline(x + i, y + i, w - 2 * i, h - 2 * i, argb(rgb, alpha * falloff * falloff));
		}
	}

	/** Type badge (spec §4): Cobblemon's primary color, black/white text by luminance, 1 px dark border, rounded corners. Returns its width. */
	private int drawTypeBadge(GuiGraphics g, ElementalType type, int x, int y) {
		return drawTypeBadge(g, type, x, y, 1f);
	}

	/** Same badge with its text at {@code textScale} (2 for the enlarged Téracristal value); height grows with it. */
	private int drawTypeBadge(GuiGraphics g, ElementalType type, float xf, float yf, float textScale) {
		int x = Math.round(xf);
		int y = Math.round(yf);
		String label = upper(type.getDisplayName().getString());
		int w = typeBadgeWidth(type, textScale);
		int h = Math.round(7 * textScale) + 12;
		int bg = type.getPrimaryColor() | 0xFF000000;
		g.fill(x + 1, y + 1, x + w - 1, y + h - 1, bg);
		g.fill(x + 1, y, x + w - 1, y + 1, BADGE_BORDER);
		g.fill(x + 1, y + h - 1, x + w - 1, y + h, BADGE_BORDER);
		g.fill(x, y + 1, x + 1, y + h - 1, BADGE_BORDER);
		g.fill(x + w - 1, y + 1, x + w, y + h - 1, BADGE_BORDER);
		drawText(g, label, x + 8, y + 6, textScale, 0xFF000000 | PokemonGuiRendering.readableTextColor(bg), true, 0.5f);
		return w;
	}

	private int typeBadgeWidth(ElementalType type, float textScale) {
		return Math.round(textWidth(upper(type.getDisplayName().getString()), textScale, true, 0.5f)) + 16;
	}

	private void drawGender(GuiGraphics g, PokemonGender gender, float x, float y, float textScale) {
		if (gender == PokemonGender.MALE) {
			drawText(g, "♂", x, y, textScale, MALE, false, 0f);
		} else if (gender == PokemonGender.FEMALE) {
			drawText(g, "♀", x, y, textScale, FEMALE, false, 0f);
		}
	}

	private void enableCanvasScissor(GuiGraphics g, int x, int y, int w, int h) {
		g.enableScissor(
				Math.round(originX + x * scale), Math.round(originY + y * scale),
				Math.round(originX + (x + w) * scale), Math.round(originY + (y + h) * scale));
	}

	private void drawCentered(GuiGraphics g, String text, float centerX, float y, float textScale, int color, boolean bold, float spacing) {
		drawText(g, text, centerX - textWidth(text, textScale, bold, spacing) / 2f, y, textScale, color, bold, spacing);
	}

	/** Draws {@code text} with its glyph top at {@code y}, optionally with CSS-like {@code letter-spacing} (canvas px). */
	private void drawText(GuiGraphics g, String text, float x, float y, float textScale, int color, boolean bold, float spacing) {
		if (text == null || text.isEmpty() || (color >>> 24) < 8) {
			return;
		}
		PoseStack pose = g.pose();
		pose.pushPose();
		pose.translate(x, y, 0);
		pose.scale(textScale, textScale, 1f);
		if (spacing <= 0f) {
			g.drawString(font, styled(text, bold), 0, 0, color, false);
		} else {
			float cursor = 0f;
			int i = 0;
			while (i < text.length()) {
				int codePoint = text.codePointAt(i);
				String glyph = new String(Character.toChars(codePoint));
				pose.pushPose();
				pose.translate(cursor, 0, 0);
				g.drawString(font, styled(glyph, bold), 0, 0, color, false);
				pose.popPose();
				cursor += font.width(styled(glyph, bold)) + spacing / textScale;
				i += Character.charCount(codePoint);
			}
		}
		pose.popPose();
	}

	private void drawSequence(GuiGraphics g, FormattedCharSequence sequence, float x, float y, int color) {
		PoseStack pose = g.pose();
		pose.pushPose();
		pose.translate(x, y, 0);
		g.drawString(font, sequence, 0, 0, color, false);
		pose.popPose();
	}

	/** Rendered width in canvas px, letter-spacing included. */
	private float textWidth(String text, float textScale, boolean bold, float spacing) {
		if (text == null || text.isEmpty()) {
			return 0f;
		}
		int glyphs = text.codePointCount(0, text.length());
		return font.width(styled(text, bold)) * textScale + spacing * (glyphs - 1);
	}

	/** Truncates with "…" so the text fits in {@code maxWidth} canvas px (spec §6.2/§10: no overflowing text). */
	private String fitText(String text, float maxWidth, float textScale, boolean bold, float spacing) {
		if (text == null || textWidth(text, textScale, bold, spacing) <= maxWidth) {
			return text;
		}
		String ellipsis = "…";
		String result = text;
		while (!result.isEmpty() && textWidth(result + ellipsis, textScale, bold, spacing) > maxWidth) {
			result = result.substring(0, result.length() - 1);
		}
		return result.stripTrailing() + ellipsis;
	}

	private static MutableComponent styled(String text, boolean bold) {
		MutableComponent component = Component.literal(text);
		return bold ? component.withStyle(ChatFormatting.BOLD) : component;
	}

	private static String upper(String text) {
		return text == null ? "" : text.toUpperCase(Locale.ROOT);
	}

	private static String stripPrefix(String message) {
		return message.startsWith("[Phantasmon] ") ? message.substring("[Phantasmon] ".length()) : message;
	}

	private static int argb(int rgb, float alpha) {
		int a = Math.max(0, Math.min(255, Math.round(alpha * 255)));
		return (a << 24) | (rgb & 0xFFFFFF);
	}

	private static int withAlpha(int argbColor, float factor) {
		int a = Math.round(((argbColor >>> 24) & 0xFF) * Math.max(0f, Math.min(1f, factor)));
		return (a << 24) | (argbColor & 0xFFFFFF);
	}

	private static int lerpColor(int from, int to, float t) {
		int r = Math.round(((from >> 16) & 0xFF) + (((to >> 16) & 0xFF) - ((from >> 16) & 0xFF)) * t);
		int gr = Math.round(((from >> 8) & 0xFF) + (((to >> 8) & 0xFF) - ((from >> 8) & 0xFF)) * t);
		int b = Math.round((from & 0xFF) + ((to & 0xFF) - (from & 0xFF)) * t);
		return (r << 16) | (gr << 8) | b;
	}

	// =====================================================================
	// Pokémon data → display (Cobblemon lookups, local data only)
	// =====================================================================

	/** Nickname if set, else Cobblemon's localized species name, else the raw id capitalized. Public: also used for the trade chat summary. */
	public static String displayName(PokemonDto pokemon) {
		Object nickname = pokemon.data() == null ? null : pokemon.data().get("nickname");
		if (nickname != null && !nickname.toString().isBlank()) {
			return nickname.toString();
		}
		Species species = PokemonSpecies.INSTANCE.getByName(pokemon.species());
		if (species != null) {
			return species.getTranslatedName().getString();
		}
		String id = pokemon.species() == null ? "?" : pokemon.species();
		return id.isEmpty() ? id : id.substring(0, 1).toUpperCase(Locale.ROOT) + id.substring(1);
	}

	private static ItemStack heldItem(PokemonDto pokemon) {
		Object raw = pokemon.data() == null ? null : pokemon.data().get("heldItem");
		return raw == null ? ItemStack.EMPTY : PokemonGuiRendering.heldItemStack(raw.toString());
	}

	/** Same localization path as the PC detail panel ({@link AbilityTemplate#getDisplayName()} is a raw translation key). */
	private static String abilityLabel(String abilityId) {
		if (abilityId == null) {
			return "?";
		}
		AbilityTemplate template = Abilities.get(abilityId);
		return template != null ? Component.translatable(template.getDisplayName()).getString() : abilityId;
	}

	/** Everything a card/slot needs from Cobblemon's local data for one Pokémon, resolved once per draw. */
	private record Look(List<ElementalType> types, ElementalType teraType, PokemonGender gender) {

		static Look of(PokemonDto pokemon) {
			Species species = PokemonSpecies.INSTANCE.getByName(pokemon.species());
			FormData form = species == null ? null : formOf(species, pokemon.form());
			List<ElementalType> types = new java.util.ArrayList<>();
			ElementalType primary = form != null ? form.getPrimaryType() : species != null ? species.getPrimaryType() : null;
			ElementalType secondary = form != null ? form.getSecondaryType() : species != null ? species.getSecondaryType() : null;
			if (primary != null) {
				types.add(primary);
			}
			if (secondary != null) {
				types.add(secondary);
			}
			Map<String, Object> data = pokemon.data() != null ? pokemon.data() : Map.of();
			Object teraRaw = data.get("teraType");
			// Every Pokémon has an inherent Tera Type (its own primary type) until changed — same rule as the PC.
			ElementalType tera = teraRaw != null ? safeType(teraRaw.toString()) : primary;
			Float maleRatio = form != null ? Float.valueOf(form.getMaleRatio()) : species != null ? Float.valueOf(species.getMaleRatio()) : null;
			return new Look(types, tera, PokemonGender.resolve(data.get("gender"), maleRatio));
		}

		private static FormData formOf(Species species, String formId) {
			if (formId != null && !formId.isBlank()) {
				String wanted = formId.toLowerCase(Locale.ROOT);
				for (FormData form : species.getForms()) {
					if (wanted.equals(form.getName().toLowerCase(Locale.ROOT)) || wanted.equals(form.formOnlyShowdownId())) {
						return form;
					}
				}
			}
			return species.getStandardForm();
		}

		private static ElementalType safeType(String typeId) {
			try {
				return ElementalTypes.INSTANCE.get(typeId.toLowerCase(Locale.ROOT));
			} catch (Exception ex) {
				return null;
			}
		}
	}

	@SuppressWarnings("unchecked")
	private static Map<String, Object> asMap(Object value) {
		return value instanceof Map ? (Map<String, Object>) value : Map.of();
	}

	@SuppressWarnings("unchecked")
	private static List<Object> asList(Object value) {
		return value instanceof List ? (List<Object>) value : List.of();
	}

	private static int asInt(Object value) {
		return value instanceof Number number ? number.intValue() : 0;
	}
}
