package com.mystaria.phantasmon.client.gui;

import java.util.List;
import java.util.Locale;
import java.util.Map;

import com.cobblemon.mod.common.api.abilities.Abilities;
import com.cobblemon.mod.common.api.abilities.AbilityTemplate;
import com.cobblemon.mod.common.api.moves.MoveTemplate;
import com.cobblemon.mod.common.api.moves.Moves;
import com.cobblemon.mod.common.api.pokemon.PokemonSpecies;
import com.cobblemon.mod.common.api.types.ElementalType;
import com.cobblemon.mod.common.api.types.ElementalTypes;
import com.cobblemon.mod.common.pokemon.FormData;
import com.cobblemon.mod.common.pokemon.Species;
import com.mojang.blaze3d.systems.RenderSystem;
import com.mojang.blaze3d.vertex.PoseStack;

import net.minecraft.ChatFormatting;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.MutableComponent;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.FormattedCharSequence;
import net.minecraft.world.item.ItemStack;

import com.mystaria.phantasmon.client.pokemon.HiddenPowerCalculator;
import com.mystaria.phantasmon.client.pokemon.NatureModifiers;
import com.mystaria.phantasmon.client.pokemon.PokemonDto;
import com.mystaria.phantasmon.client.pokemon.PokemonGender;

/**
 * Phantasmon's screen "design system" (Adrien 2026-10-02): everything the
 * live trade screen established — and that the PC screen now reuses so both
 * share one art direction — lives here.
 *
 * <p><b>Coordinates</b>: subclasses lay everything out in the handoff
 * mock-up's own 1600×900 px space ({@code Documentation/design/trade-screen/}). The
 * canvas is drawn through one pose scale of {@code s/2 × MENU_SCALE} GUI
 * units per px, {@code s = min(1, width/800, height/450)} (trade spec §2),
 * centered. Mouse positions go back through {@link #toCanvasX}/{@link #toCanvasY}
 * before any hit test.
 *
 * <p><b>Text</b>: Minecraft's font only stays crisp at integer scales — titles
 * and values use scale 2, small labels scale 1.
 *
 * <p><b>Draw order</b>: in 1.21.1 {@code fill}/{@code drawString} are batched
 * while {@code blit} draws immediately, so a texture blitted after a fill
 * would end up <em>under</em> it. {@link #blitTexture} therefore always
 * {@code flush()}es first, which keeps the code order the visual order.
 * Modal windows are drawn at z=2000, above item icons and 3D models.
 *
 * <p>Gradients/halos the vanilla GUI can't draw are the PNGs generated by
 * {@code scripts/generate_trade_textures.py} from the mock-up's exact CSS.
 */
public abstract class PhantasmonCanvasScreen extends Screen {

	protected static final int CANVAS_W = 1600;
	protected static final int CANVAS_H = 900;

	// ---- Textures (scripts/generate_trade_textures.py) ----
	protected static final Texture TEX_BACKGROUND = new Texture("background", 400, 225);
	protected static final Texture TEX_RAIL = new Texture("rail", 97, 379);
	protected static final Texture TEX_CARD = new Texture("card", 288, 379);
	protected static final Texture TEX_HEAD_LEFT = new Texture("player_head_left", 344, 24);
	protected static final Texture TEX_HEAD_RIGHT = new Texture("player_head_right", 344, 24);
	protected static final Texture TEX_VIEWPORT = new Texture("viewport", 575, 235);
	protected static final Texture TEX_MODAL = new Texture("modal", 260, 133);
	protected static final Texture TEX_SHADOW = new Texture("shadow", 64, 16);
	protected static final ResourceLocation SPRITE_STAR = ResourceLocation.fromNamespaceAndPath("phantasmon", "pc/star");

	// ---- Colors (trade spec §4, ARGB) ----
	protected static final int CYAN = 0xFF50E6FF;
	protected static final int CYAN2 = 0xFF2FB7C9;
	protected static final int WHITE = 0xFFFFFFFF;
	protected static final int MUTED = 0xFF9FD9E6;
	protected static final int DIM = 0xFF999999;
	protected static final int TITLE = 0xFF5FE6F2;
	protected static final int TEXT2 = 0xFFCCCCCC;
	protected static final int IV_COLOR = 0xFF88CCFF;
	protected static final int EV_COLOR = 0xFFFFCC88;
	protected static final int STAT_HEAD = 0xFF6C8C96;
	protected static final int SLOT_TOP = 0xFFCBEAF0;
	protected static final int MALE = 0xFF50BFFF;
	protected static final int FEMALE = 0xFFFF7594;
	protected static final int STAR = 0xFFFFDD33;
	protected static final int ACCENT_LEFT = 0xFF50BFFF;
	protected static final int ACCENT_RIGHT = 0xFFFF6688;
	protected static final int READY_BORDER = 0xFF76FFB0;
	protected static final int READY_TEXT = 0xFFBAFFD2;
	protected static final int DANGER_BORDER = 0xFFFF5078;
	protected static final int ERROR_TEXT = 0xFFFFAA66;

	protected static final int PANEL_FILL = 0x69081422;
	protected static final int PANEL_BORDER = 0xBF50E6FF;
	protected static final int PANEL_INNER = 0x1F50E6FF;
	protected static final int RAIL_BORDER = 0x7A50E6FF;
	protected static final int LINE_12 = 0x1F50E6FF;
	protected static final int LINE_20 = 0x3350E6FF;
	protected static final int LINE_25 = 0x4050E6FF;
	protected static final int LINE_28 = 0x4750E6FF;
	protected static final int LINE_30 = 0x4D50E6FF;
	protected static final int RAIL_FOOT_BG = 0x33000000;
	protected static final int CARD_HEAD_BG = 0x6B02080F;
	protected static final int INFO_BOX_BG = 0x6100080F;
	protected static final int MOVE_BG = 0xFF07131F;
	protected static final int STAT_EVEN_BG = 0x08FFFFFF;
	protected static final int FOOTER_BG = 0xD1030A14;
	protected static final int SLOT_BG = 0x820E3C4E;
	protected static final int SLOT_BORDER = 0x5950E6FF;
	protected static final int SLOT_HOVER_BG = 0x5950E6FF;
	protected static final int SLOT_SELECTED_BG = 0x7350E6FF;
	protected static final int VEIL = 0xD100050A;
	protected static final int BADGE_BORDER = 0x54000000;

	protected static final int[] STD_BUTTON = { 0xFF18466B, 0xFF0D2A42 };
	protected static final int[] STD_BUTTON_HOVER = { 0xFF205C8D, 0xFF123859 };
	protected static final int[] DANGER_BUTTON = { 0xFF6B182A, 0xFF420D18 };
	protected static final int[] DANGER_BUTTON_HOVER = { 0xFF8D2038, 0xFF591222 };

	/** The whole canvas is drawn at 80% of the spec's size (Adrien 2026-10-02: full-screen was too big), still centered. */
	protected static final float MENU_SCALE = 0.8f;
	/** Text scale of the card's values (item, nature, ability, moves, IV/EV) — scale 1 was too small to read (Adrien 2026-10-02). */
	protected static final float VALUE_SCALE = 2f;
	protected static final int NATURE_UP = 0xFFFF8A80;
	protected static final int NATURE_DOWN = 0xFF80B4FF;

	// ---- 3D model tuning (confirmed in game by Adrien on the trade screen, 2026-10-02) ----
	/** Outer pose scale of a rail slot's model, in canvas px space (×1.5 after Adrien's first test). */
	protected static final float SLOT_MODEL_SCALE = 5.5f * 1.5f;
	/** Outer pose scale of a card's model (Z15), in canvas px space. */
	protected static final float CARD_MODEL_SCALE = 19f;
	/**
	 * The model hangs below its anchor: its visual center sits about
	 * {@code MODEL_CENTER_K × outerScale} px under it (value implied by the PC
	 * screen's tuned ratio). The anchor is derived from the box center with it,
	 * so the model stays centered when its scale changes.
	 */
	protected static final float MODEL_CENTER_K = 7.9f;
	/** Extra downward shift in canvas px at the reference scales above — 20/40 confirmed in game by Adrien. Other slot sizes scale it proportionally. */
	protected static final float SLOT_MODEL_OFFSET = 20f;
	protected static final float CARD_MODEL_OFFSET = 40f;

	protected static final float FLOAT_PERIOD_MS = 3500f;
	protected static final String[] STAT_KEYS = { "hp", "atk", "def", "spa", "spd", "spe" };

	/** Card zone geometry (trade spec Z12-Z25), card's left edge at {@code 219 + dx}. */
	protected static final int CARD_X = 219;

	protected final long openedAt = System.currentTimeMillis();
	protected float scale;
	protected float originX;
	protected float originY;

	protected PhantasmonCanvasScreen(Component title) {
		super(title);
	}

	@Override
	protected void init() {
		float s = Math.min(1f, Math.min(this.width / 800f, this.height / 450f));
		scale = s / 2f * MENU_SCALE;
		originX = (this.width - CANVAS_W * scale) / 2f;
		originY = (this.height - CANVAS_H * scale) / 2f;
	}

	@Override
	public boolean isPauseScreen() {
		return false;
	}

	@Override
	public void renderBackground(GuiGraphics graphics, int mouseX, int mouseY, float partialTick) {
		// Drawn explicitly by renderWorldBackdrop() — a no-op here so nothing ever draws it twice.
	}

	/** The (blurred, dimmed) game around the 80% canvas. */
	protected void renderWorldBackdrop(GuiGraphics graphics, int mouseX, int mouseY, float partialTick) {
		super.renderBackground(graphics, mouseX, mouseY, partialTick);
	}

	protected void beginCanvas(GuiGraphics g) {
		PoseStack pose = g.pose();
		pose.pushPose();
		pose.translate(originX, originY, 0);
		pose.scale(scale, scale, 1f);
	}

	protected void endCanvas(GuiGraphics g) {
		g.pose().popPose();
	}

	protected double toCanvasX(double guiX) {
		return (guiX - originX) / scale;
	}

	protected double toCanvasY(double guiY) {
		return (guiY - originY) / scale;
	}

	protected static boolean inside(double x, double y, int bx, int by, int bw, int bh) {
		return x >= bx && x < bx + bw && y >= by && y < by + bh;
	}

	// =====================================================================
	// Shared building blocks
	// =====================================================================

	/** Z01: page background, translucent fill, 2 px cyan border + 1 px inner line, the two neon bars across the top edge. */
	protected void renderRootPanel(GuiGraphics g) {
		blitTexture(g, TEX_BACKGROUND, 0, 0, CANVAS_W, CANVAS_H);
		g.fill(0, 0, CANVAS_W, CANVAS_H, PANEL_FILL);
		g.fill(0, 0, CANVAS_W, 2, PANEL_BORDER);
		g.fill(0, CANVAS_H - 2, CANVAS_W, CANVAS_H, PANEL_BORDER);
		g.fill(0, 2, 2, CANVAS_H - 2, PANEL_BORDER);
		g.fill(CANVAS_W - 2, 2, CANVAS_W, CANVAS_H - 2, PANEL_BORDER);
		outline(g, 2, 2, CANVAS_W - 4, CANVAS_H - 4, PANEL_INNER);
		int barWidth = Math.round(CANVAS_W * 0.34f);
		for (int barX : new int[] { 0, CANVAS_W - barWidth }) {
			g.fillGradient(barX, -15, barX + barWidth, -2, 0x0050E6FF, 0x5550E6FF);
			g.fill(barX, -2, barX + barWidth, 2, CYAN);
			g.fillGradient(barX, 2, barX + barWidth, 15, 0x5550E6FF, 0x0050E6FF);
		}
	}

	/** Z02 / Z04: the two outward-gradient header plates. */
	protected void renderHeaderPlates(GuiGraphics g) {
		renderHeaderPlates(g, 688);
	}

	/**
	 * Header plates: left one from x=15, right one ending at x=1585, each {@code plateWidth} wide, so the free gap
	 * between them stays centered on the canvas (x=800) whatever the width.
	 */
	protected void renderHeaderPlates(GuiGraphics g, int plateWidth) {
		blitTexture(g, TEX_HEAD_LEFT, 15, 15, plateWidth, 48);
		outline(g, 15, 15, plateWidth, 48, CYAN2);
		blitTexture(g, TEX_HEAD_RIGHT, 1585 - plateWidth, 15, plateWidth, 48);
		outline(g, 1585 - plateWidth, 15, plateWidth, 48, CYAN2);
	}

	/** IMPORTER + EXPORTER pair (PC and editor headers), centered on x=800 between narrower header plates. */
	protected static final int HEADER_PAIR_W = 170;
	protected static final int HEADER_PAIR_GAP = 10;
	protected static final int HEADER_IMPORT_X = 800 - HEADER_PAIR_GAP / 2 - HEADER_PAIR_W;
	protected static final int HEADER_EXPORT_X = 800 + HEADER_PAIR_GAP / 2;
	/** Same 12 px margin between plate and button as the single centered ÉCHANGER button. */
	protected static final int HEADER_PAIR_PLATE_W = HEADER_IMPORT_X - 12 - 15;
	/** Room left for the title inside the narrower left plate. */
	protected static final int HEADER_PAIR_TITLE_W = HEADER_PAIR_PLATE_W - 38;

	/** Z03-style primary action button (ÉCHANGER / IMPORTER): glow, gradient, cyan border. */
	protected void renderPrimaryButtonFrame(GuiGraphics g, int x, int y, int w, int h, boolean hovered, boolean green) {
		int[] gradient = hovered ? STD_BUTTON_HOVER : STD_BUTTON;
		glowOutside(g, x, y, w, h, green ? 0x76FFB0 : 0x50E6FF, green ? 0.3f : 0.18f, 8);
		g.fillGradient(x, y, x + w, y + h, gradient[0], gradient[1]);
		outline(g, x, y, w, h, green ? READY_BORDER : CYAN);
	}

	/** Rail frame (Z05): gradient, border, spaced uppercase title with its separator, and the 2-line hint box at the bottom (Z11). */
	protected void renderRailFrame(GuiGraphics g, int x, int y, int w, int h, String title, Component hint) {
		blitTexture(g, TEX_RAIL, x, y, w, h);
		outline(g, x, y, w, h, RAIL_BORDER);
		drawText(g, fitText(upper(title), w - 22, 1f, false, 2f), x + 13, y + 17, 1f, MUTED, false, 2f);
		g.fill(x + 9, y + 36, x + w - 9, y + 36 + hairline(), LINE_25);
		if (hint == null) {
			return;
		}
		int footY = y + h - 49;
		g.fill(x + 9, footY, x + w - 9, footY + 40, RAIL_FOOT_BG);
		outline(g, x + 9, footY, w - 18, 40, LINE_25);
		float lineScale = snapTextScale(1f);
		List<FormattedCharSequence> lines = font.split(hint, (int) ((w - 32) / lineScale));
		int lineCount = Math.min(2, lines.size());
		float lineHeight = 9 * lineScale;
		float lineY = footY + (40 - lineCount * lineHeight) / 2f + 1;
		for (int i = 0; i < lineCount; i++) {
			float width = sequenceWidth(lines.get(i));
			drawSequence(g, lines.get(i), x + 9 + (w - 18 - width) / 2f, lineY + i * lineHeight, DIM);
		}
	}

	protected enum SlotLook { NORMAL, HOVER, SELECTED, DRAG_SOURCE }

	/**
	 * Where things go inside one slot, relative to its top-left corner: the
	 * model area (scissored), the name baseline and the held-item icon.
	 */
	protected record SlotLayout(int modelTop, int modelHeight, float modelScale, int nameY, int itemX, int itemY, int itemSize) {
	}

	/** Trade rail slot (Z08, 85×214): models ×1.5 the spec's 72 px icon, name pushed under them. */
	protected static final SlotLayout RAIL_SLOT = new SlotLayout(18, 142, SLOT_MODEL_SCALE, 164, 59, 188, 20);

	/**
	 * One Pokémon slot: gender + level on top, live 3D model, name (★ if
	 * shiny), held item. Empty slots keep the normal look (trade spec §6.2);
	 * a drag source keeps its frame but hides its content (the model follows
	 * the cursor instead).
	 */
	protected void renderSlot(GuiGraphics g, int x, int y, int w, int h, PokemonDto pokemon, SlotLook look, SlotLayout layout) {
		switch (look) {
			case SELECTED -> {
				g.fill(x, y, x + w, y + h, SLOT_SELECTED_BG);
				glowInside(g, x, y, w, h, 0x50E6FF, 0.35f, 7);
				outline(g, x, y, w, h, WHITE);
			}
			case HOVER -> {
				g.fill(x, y, x + w, y + h, SLOT_HOVER_BG);
				outline(g, x, y, w, h, CYAN);
			}
			case DRAG_SOURCE -> {
				g.fill(x, y, x + w, y + h, SLOT_BG);
				glowInside(g, x, y, w, h, 0x50E6FF, 0.2f, 4);
				outline(g, x, y, w, h, CYAN2);
			}
			default -> {
				g.fill(x, y, x + w, y + h, SLOT_BG);
				outline(g, x, y, w, h, SLOT_BORDER);
			}
		}
		if (pokemon == null || look == SlotLook.DRAG_SOURCE) {
			return;
		}
		Look info = Look.of(pokemon);

		drawGender(g, info.gender(), x + 6, y + 6, 1f);
		String level = Component.translatable("phantasmon.trade.screen.level_short", pokemon.level()).getString();
		drawText(g, level, x + w - 6 - textWidth(level, 1f, false, 0f), y + 6, 1f, SLOT_TOP, false, 0f);

		int modelTop = y + layout.modelTop();
		g.flush();
		enableCanvasScissor(g, x + 1, modelTop, w - 2, layout.modelHeight());
		PokemonGuiRendering.renderModel(g, pokemon.species(), pokemon.form(), pokemon.isShiny(), PokemonGuiRendering.storedGender(pokemon),
				x + w / 2f, slotModelAnchorY(modelTop + layout.modelHeight() / 2f, layout.modelScale()), layout.modelScale());
		g.disableScissor();

		String starPrefix = pokemon.isShiny() ? "★ " : "";
		float starWidth = textWidth(starPrefix, 1f, true, 0f);
		String name = fitText(displayName(pokemon), w - 10 - starWidth, 1f, true, 0f);
		float nameStart = x + (w - starWidth - textWidth(name, 1f, true, 0f)) / 2f;
		if (!starPrefix.isEmpty()) {
			drawText(g, starPrefix, nameStart, y + layout.nameY(), 1f, STAR, true, 0f);
		}
		drawText(g, name, nameStart + starWidth, y + layout.nameY(), 1f, WHITE, true, 0f);

		ItemStack item = heldItem(pokemon);
		if (!item.isEmpty()) {
			PokemonGuiRendering.renderItemIcon(g, item, x + layout.itemX(), y + layout.itemY(), layout.itemSize());
		}
	}

	/** A slot model's anchor: same centering as the rail slots, with the confirmed offset scaled to this model's size. */
	protected static float slotModelAnchorY(float boxCenterY, float outerScale) {
		return modelAnchorY(boxCenterY, outerScale, SLOT_MODEL_OFFSET * outerScale / SLOT_MODEL_SCALE);
	}

	/** Anchor that puts the model's visual center on {@code boxCenterY} — see {@link #MODEL_CENTER_K}. */
	protected static float modelAnchorY(float boxCenterY, float outerScale, float offset) {
		return boxCenterY - MODEL_CENTER_K * outerScale + offset;
	}

	// ---- Pokémon card (trade spec Z12-Z25) ----

	/**
	 * Full Pokémon card at {@code CARD_X + dx}: head, 3D viewport, info block.
	 * {@code emptyMessage} is shown centered when {@code pokemon} is null.
	 * {@code showHiddenPower} adds the Hidden Power type next to the Tera type
	 * (PC only — it was already part of the old PC detail panel).
	 */
	protected void renderPokemonCard(GuiGraphics g, PokemonDto pokemon, String owner, int dx, int accent,
			String emptyMessage, boolean showHiddenPower) {
		blitTexture(g, TEX_CARD, CARD_X + dx, 72, 577, 758);
		outline(g, CARD_X + dx, 72, 577, 758, CYAN2);
		g.fill(CARD_X + dx, 72, 796 + dx, 75, accent);

		if (pokemon == null) {
			if (emptyMessage != null) {
				drawText(g, emptyMessage, CARD_X + dx + (577 - textWidth(emptyMessage, 1f, false, 0f)) / 2f, 447, 1f, DIM, false, 0f);
			}
			return;
		}
		Look info = Look.of(pokemon);
		renderCardHead(g, pokemon, info, owner, dx);
		renderViewport(g, pokemon, info, dx);
		renderInfo(g, pokemon, info, dx, showHiddenPower);
	}

	/** Z13: name + gender left, owner centered between them (flex space-between), "Nv. X" right. */
	private void renderCardHead(GuiGraphics g, PokemonDto pokemon, Look info, String owner, int dx) {
		g.fill(220 + dx, 75, 795 + dx, 117, CARD_HEAD_BG);
		g.fill(220 + dx, 117 - hairline(), 795 + dx, 117, LINE_28);

		String level = Component.translatable("phantasmon.trade.screen.level", pokemon.level()).getString();
		// Not bold: the modpack's font renders bold wider than Minecraft measures it, which pushed this right-aligned text out of the card.
		float levelWidth = textWidth(level, 2f, false, 0f);
		float levelX = 784 + dx - levelWidth;
		String ownerText = upper(owner);
		float ownerWidth = textWidth(ownerText, 1f, false, 1.5f);

		float genderWidth = info.gender() == PokemonGender.MALE || info.gender() == PokemonGender.FEMALE ? 14 : 0;
		float nameMax = Math.max(40, (levelX - (231 + dx)) - ownerWidth - genderWidth - 24);
		String name = fitText(displayName(pokemon), nameMax, 2f, true, 0.6f);
		float nameWidth = textWidth(name, 2f, true, 0.6f);
		drawText(g, name, 231 + dx, 89, 2f, WHITE, true, 0.6f);
		drawGender(g, info.gender(), 231 + dx + nameWidth + 6, 93, 1f);

		float nameRight = 231 + dx + nameWidth + genderWidth;
		float ownerX = nameRight + (levelX - nameRight - ownerWidth) / 2f;
		drawText(g, ownerText, ownerX, 93, 1f, MUTED, false, 1.5f);
		drawText(g, level, levelX, 89, 2f, WHITE, false, 0f);
	}

	/** Z14-Z16: halo/grid background, type badges, shiny star, floating 3D model with its shadow. */
	private void renderViewport(GuiGraphics g, PokemonDto pokemon, Look info, int dx) {
		blitTexture(g, TEX_VIEWPORT, 220 + dx, 117, 575, 235);

		int badgeX = 229 + dx;
		for (ElementalType type : info.types()) {
			badgeX += drawTypeBadge(g, type, badgeX, 126, VALUE_SCALE) + 6;
		}
		if (pokemon.isShiny()) {
			g.flush();
			g.blitSprite(SPRITE_STAR, 795 + dx - 10 - 18, 125, 18, 18);
		}

		float t = (System.currentTimeMillis() - openedAt) % FLOAT_PERIOD_MS / FLOAT_PERIOD_MS;
		float ease = (1f - (float) Math.cos(t * 2 * Math.PI)) / 2f;
		blitTexture(g, TEX_SHADOW, 437 + dx, 318, 140, 26);

		g.flush();
		enableCanvasScissor(g, 220 + dx, 117, 575, 235);
		PoseStack pose = g.pose();
		pose.pushPose();
		float centerX = 220 + dx + 575 / 2f;
		float anchorY = modelAnchorY(117 + 235 / 2f, CARD_MODEL_SCALE, CARD_MODEL_OFFSET);
		pose.translate(centerX, anchorY - 5f * ease, 0);
		float grow = 1f + 0.015f * ease;
		pose.scale(grow, grow, 1f);
		PokemonGuiRendering.renderModel(g, pokemon.species(), pokemon.form(), pokemon.isShiny(), PokemonGuiRendering.storedGender(pokemon), 0, 0, CARD_MODEL_SCALE);
		pose.popPose();
		g.disableScissor();
	}

	/**
	 * Z17-Z25, enlarged after Adrien's first trade test (2026-10-02): every
	 * value is drawn at {@link #VALUE_SCALE} and the boxes are re-spread over
	 * the whole info block. Each move gets its type badge; the nature shows its
	 * +/- stats, mirrored by colored stat labels in the IV/EV box.
	 */
	private void renderInfo(GuiGraphics g, PokemonDto pokemon, Look info, int dx, boolean showHiddenPower) {
		g.fill(220 + dx, 352, 795 + dx, 352 + hairline(), LINE_20);
		Map<String, Object> data = pokemon.data() != null ? pokemon.data() : Map.of();

		// Z18 Objet tenu
		infoBox(g, 228 + dx, 361, 276, 56, "phantasmon.trade.screen.held_item");
		float valueY = 361 + 25;
		ItemStack item = heldItem(pokemon);
		String itemText;
		float valueX = 237 + dx;
		if (!item.isEmpty()) {
			PokemonGuiRendering.renderItemIcon(g, item, valueX, valueY - 3, 20);
			valueX += 26;
			itemText = item.getHoverName().getString();
		} else {
			Object raw = data.get("heldItem");
			itemText = raw != null && !raw.toString().isBlank() ? raw.toString()
					: Component.translatable("phantasmon.trade.screen.no_item").getString();
		}
		drawText(g, fitText(itemText, 504 + dx - 9 - valueX, VALUE_SCALE, false, 0f), valueX, valueY, VALUE_SCALE, WHITE, false, 0f);

		// Z19 Nature (+ its boosted/lowered stats, small, after the name)
		infoBox(g, 510 + dx, 361, 276, 56, "phantasmon.trade.screen.nature");
		// +boosted (red) / -lowered (blue) at the same size as the value — scale 1 was unreadable (Adrien 2026-10-02).
		NatureModifiers.Modifier modifier = NatureModifiers.get(pokemon.nature());
		float modifierWidth = 0f;
		if (modifier != null) {
			String up = "+" + modifier.boosted();
			String down = "-" + modifier.reduced();
			float downWidth = textWidth(down, VALUE_SCALE, false, 0f);
			float upWidth = textWidth(up, VALUE_SCALE, false, 0f);
			drawText(g, down, 777 + dx - downWidth, valueY, VALUE_SCALE, NATURE_DOWN, false, 0f);
			drawText(g, up, 777 + dx - downWidth - 10 - upWidth, valueY, VALUE_SCALE, NATURE_UP, false, 0f);
			modifierWidth = upWidth + 10 + downWidth;
		}
		String nature = fitText(NatureModifiers.displayName(pokemon.nature()), 258 - (modifierWidth > 0 ? modifierWidth + 12 : 0), VALUE_SCALE, false, 0f);
		drawText(g, nature, 519 + dx, valueY, VALUE_SCALE, WHITE, false, 0f);

		// Z20 Talent, Z21 Téracristal (+ Hidden Power on the right, PC only)
		infoBox(g, 228 + dx, 424, 276, 56, "phantasmon.trade.screen.ability");
		valueY = 424 + 25;
		drawText(g, fitText(abilityLabel(pokemon.ability()), 258, VALUE_SCALE, false, 0f), 237 + dx, valueY, VALUE_SCALE, WHITE, false, 0f);
		infoBox(g, 510 + dx, 424, 276, 56, "phantasmon.trade.screen.tera");
		if (info.teraType() != null) {
			drawTypeBadge(g, info.teraType(), 519 + dx, valueY - 3, VALUE_SCALE);
		}
		if (showHiddenPower) {
			ElementalType hiddenPower = Look.safeType(HiddenPowerCalculator.type(asMap(data.get("ivs"))));
			String label = upper(Component.translatable("phantasmon.pc.screen.hidden_power").getString());
			drawText(g, label, 777 + dx - textWidth(label, 1f, true, 1.2f), 432, 1f, TITLE, true, 1.2f);
			if (hiddenPower != null) {
				int w = typeBadgeWidth(hiddenPower, VALUE_SCALE);
				drawTypeBadge(g, hiddenPower, 777 + dx - w, valueY - 3, VALUE_SCALE);
			}
		}

		// Z22-Z23 Capacités: 4 tall rows, name left + type badge right, empty rows kept
		infoBox(g, 228 + dx, 488, 303, 333, "phantasmon.trade.screen.moves");
		List<Object> moves = asList(data.get("moves"));
		for (int i = 0; i < 4; i++) {
			int rowY = 512 + i * 76;
			int rowH = 68;
			g.fill(237 + dx, rowY, 522 + dx, rowY + rowH, MOVE_BG);
			outline(g, 237 + dx, rowY, 285, rowH, LINE_12);
			if (i >= moves.size()) {
				continue;
			}
			// Name on top, its type badge (same size as the other badges) underneath — side by side the badge
			// had to stay tiny to leave room for the name (Adrien 2026-10-02).
			String moveId = moves.get(i).toString();
			MoveTemplate template = Moves.INSTANCE.getByName(moveId);
			boolean hasType = template != null && template.getElementalType() != null;
			int badgeHeight = typeBadgeHeight(VALUE_SCALE);
			float nameHeight = 7 * snapTextScale(VALUE_SCALE);
			float blockTop = rowY + (rowH - nameHeight - (hasType ? 6 + badgeHeight : 0)) / 2f;
			String move = fitText(template != null ? template.getDisplayName().getString() : moveId, 265, VALUE_SCALE, false, 0f);
			drawText(g, move, 247 + dx, blockTop, VALUE_SCALE, TEXT2, false, 0f);
			if (hasType) {
				drawTypeBadge(g, template.getElementalType(), 247 + dx, blockTop + nameHeight + 6, VALUE_SCALE);
			}
		}

		// Z24-Z25 IV / EV
		infoBox(g, 538 + dx, 488, 248, 333, "phantasmon.trade.screen.ivs_evs");
		int ivRight = 712 + dx;
		int evRight = 774 + dx;
		String ivHead = Component.translatable("phantasmon.trade.screen.iv").getString();
		String evHead = Component.translatable("phantasmon.trade.screen.ev").getString();
		drawText(g, ivHead, ivRight - textWidth(ivHead, 1f, true, 0f), 514, 1f, STAT_HEAD, true, 0f);
		drawText(g, evHead, evRight - textWidth(evHead, 1f, true, 0f), 514, 1f, STAT_HEAD, true, 0f);
		Map<String, Object> ivs = asMap(data.get("ivs"));
		Map<String, Object> evs = asMap(data.get("evs"));
		String boosted = modifier == null ? null : modifier.boosted().toLowerCase(Locale.ROOT);
		String reduced = modifier == null ? null : modifier.reduced().toLowerCase(Locale.ROOT);
		int rowH = 36;
		int evTotal = 0;
		for (int i = 0; i < STAT_KEYS.length; i++) {
			int rowY = 528 + i * rowH;
			if (i % 2 == 1) {
				g.fill(547 + dx, rowY, 777 + dx, rowY + rowH, STAT_EVEN_BG);
			}
			float textY = rowY + (rowH - 7 * VALUE_SCALE) / 2f;
			int labelColor = STAT_KEYS[i].equals(boosted) ? NATURE_UP : STAT_KEYS[i].equals(reduced) ? NATURE_DOWN : WHITE;
			String label = fitText(Component.translatable("phantasmon.trade.screen.stat." + STAT_KEYS[i]).getString(),
					ivRight - 36 - (551 + dx) - 8, VALUE_SCALE, false, 0f);
			drawText(g, label, 551 + dx, textY, VALUE_SCALE, labelColor, false, 0f);
			String iv = String.valueOf(asInt(ivs.get(STAT_KEYS[i])));
			int evValue = asInt(evs.get(STAT_KEYS[i]));
			evTotal += evValue;
			String ev = String.valueOf(evValue);
			drawText(g, iv, ivRight - textWidth(iv, VALUE_SCALE, false, 0f), textY, VALUE_SCALE, IV_COLOR, false, 0f);
			drawText(g, ev, evRight - textWidth(ev, VALUE_SCALE, false, 0f), textY, VALUE_SCALE, EV_COLOR, false, 0f);
		}
		int totalY = 528 + 6 * rowH + 6;
		g.fill(547 + dx, totalY, 777 + dx, totalY + hairline(), LINE_20);
		float totalTextY = totalY + 1 + (rowH - 7 * VALUE_SCALE) / 2f;
		drawText(g, Component.translatable("phantasmon.trade.screen.total_ev").getString(), 551 + dx, totalTextY, VALUE_SCALE, DIM, false, 0f);
		String total = String.valueOf(evTotal);
		drawText(g, total, evRight - textWidth(total, VALUE_SCALE, false, 0f), totalTextY, VALUE_SCALE, EV_COLOR, false, 0f);
	}

	protected void infoBox(GuiGraphics g, int x, int y, int w, int h, String labelKey) {
		g.fill(x, y, x + w, y + h, INFO_BOX_BG);
		outline(g, x, y, w, h, LINE_20);
		drawText(g, upper(Component.translatable(labelKey).getString()), x + 9, y + 8, 1f, TITLE, true, 1.2f);
	}

	// ---- Footer, buttons, modals ----

	/** Z28: footer bar with an optional status line on the left (scale 2). */
	protected void renderFooterBar(GuiGraphics g, String status, int statusColor, float statusMaxWidth) {
		g.fill(15, 839, 1585, 886, FOOTER_BG);
		outline(g, 15, 839, 1570, 47, LINE_30);
		if (status != null) {
			drawText(g, fitText(status, statusMaxWidth, 2f, false, 0f), 27, 855.5f, 2f, statusColor, false, 0f);
		}
	}

	protected void renderButton(GuiGraphics g, int x, int y, int w, int h, String labelKey, boolean danger, boolean hovered) {
		renderButton(g, x, y, w, h, labelKey, danger, hovered, 1f);
	}

	/** Same button with its label at {@code textScale} (2 for the PC's buttons). */
	protected void renderButton(GuiGraphics g, int x, int y, int w, int h, String labelKey, boolean danger, boolean hovered, float textScale) {
		int[] gradient = danger ? (hovered ? DANGER_BUTTON_HOVER : DANGER_BUTTON) : (hovered ? STD_BUTTON_HOVER : STD_BUTTON);
		g.fillGradient(x, y, x + w, y + h, gradient[0], gradient[1]);
		outline(g, x, y, w, h, danger ? DANGER_BORDER : CYAN);
		String label = upper(Component.translatable(labelKey).getString());
		float width = textWidth(label, textScale, true, 1.5f);
		float height = 7 * snapTextScale(textScale);
		drawText(g, label, x + (w - width) / 2f, y + (h - height) / 2f, textScale, WHITE, true, 1.5f);
	}

	/** Square danger-style close button with a ✕ (same red as QUITTER / SUPPRIMER). */
	protected void renderCloseButton(GuiGraphics g, int x, int y, int size, boolean hovered) {
		int[] gradient = hovered ? DANGER_BUTTON_HOVER : DANGER_BUTTON;
		g.fillGradient(x, y, x + size, y + size, gradient[0], gradient[1]);
		outline(g, x, y, size, size, DANGER_BORDER);
		drawCentered(g, "✕", x + size / 2f, y + (size - 7 * snapTextScale(2f)) / 2f, 2f, WHITE, false, 0f);
	}

	/** Full-screen veil then the canvas transform again, all lifted to z=2000 (above item icons/3D models drawn underneath). */
	protected void beginModalLayer(GuiGraphics g, float fade) {
		g.flush();
		PoseStack pose = g.pose();
		pose.pushPose();
		pose.translate(0, 0, 2000);
		g.fill(0, 0, this.width, this.height, withAlpha(VEIL, fade));
		pose.translate(originX, originY, 0);
		pose.scale(scale, scale, 1f);
	}

	protected void endModalLayer(GuiGraphics g) {
		g.flush();
		g.pose().popPose();
	}

	protected void renderModalCard(GuiGraphics g, int x, int y, int w, int h, float fade) {
		glowOutside(g, x, y, w, h, 0x50E6FF, 0.18f * fade, 14);
		// Flush first: the shader color tint must only apply to this one blit, not to the pending batch.
		g.flush();
		RenderSystem.setShaderColor(1f, 1f, 1f, fade);
		blitTexture(g, TEX_MODAL, x, y, w, h);
		RenderSystem.setShaderColor(1f, 1f, 1f, 1f);
		outline(g, x, y, w, h, withAlpha(CYAN, fade));
	}

	// =====================================================================
	// Drawing helpers (all in canvas px)
	// =====================================================================

	protected record Texture(ResourceLocation location, int width, int height) {
		Texture(String name, int width, int height) {
			this(ResourceLocation.fromNamespaceAndPath("phantasmon", "textures/gui/trade/" + name + ".png"), width, height);
		}
	}

	/** Stretched blit with blending on — flushes the pending fill/text batch first so code order stays draw order (see class javadoc). */
	protected static void blitTexture(GuiGraphics g, Texture texture, int x, int y, int w, int h) {
		g.flush();
		RenderSystem.enableBlend();
		RenderSystem.defaultBlendFunc();
		g.blit(texture.location(), x, y, w, h, 0f, 0f, texture.width(), texture.height(), texture.width(), texture.height());
		RenderSystem.disableBlend();
	}

	/** Screen pixels per canvas px (≈0.8-1 at usual resolutions/GUI scales, never an integer in general). */
	protected float pixelsPerCanvasPx() {
		return (float) (scale * Minecraft.getInstance().getWindow().getGuiScale());
	}

	/**
	 * Thickness, in canvas px, of a line that always covers at least one
	 * screen pixel. A literal 1 px canvas line is &lt;1 screen pixel wide once
	 * the canvas is scaled down, and the rasterizer then drops it depending on
	 * where it falls — that's what made whole panel edges and slot borders
	 * disappear on Adrien's first PC capture (2026-10-02).
	 */
	protected int hairline() {
		float ppx = pixelsPerCanvasPx();
		return ppx <= 0 ? 1 : Math.max(1, (int) Math.ceil(1f / ppx - 0.01f));
	}

	/** Rectangle border drawn with {@link #hairline()}-thick edges (replaces {@code GuiGraphics.renderOutline}). */
	protected void outline(GuiGraphics g, int x, int y, int w, int h, int color) {
		int t = hairline();
		g.fill(x, y, x + w, y + t, color);
		g.fill(x, y + h - t, x + w, y + h, color);
		g.fill(x, y + t, x + t, y + h - t, color);
		g.fill(x + w - t, y + t, x + w, y + h - t, color);
	}

	/** Approximates a CSS outer {@code box-shadow} glow with fading rings. */
	protected void glowOutside(GuiGraphics g, int x, int y, int w, int h, int rgb, float alpha, int size) {
		int t = hairline();
		for (int i = t; i <= size; i += t) {
			float falloff = 1f - (i - t) / (float) size;
			outline(g, x - i, y - i, w + 2 * i, h + 2 * i, argb(rgb, alpha * falloff * falloff));
		}
	}

	/** Same for an {@code inset} glow (selected slot). */
	protected void glowInside(GuiGraphics g, int x, int y, int w, int h, int rgb, float alpha, int size) {
		int t = hairline();
		for (int i = t; i <= size; i += t) {
			float falloff = 1f - (i - t) / (float) size;
			outline(g, x + i, y + i, w - 2 * i, h - 2 * i, argb(rgb, alpha * falloff * falloff));
		}
	}

	/** Type badge (trade spec §4): Cobblemon's primary color, black/white text by luminance, 1 px dark border, rounded corners. Returns its width. */
	protected int drawTypeBadge(GuiGraphics g, ElementalType type, int x, int y) {
		return drawTypeBadge(g, type, x, y, 1f);
	}

	/** Same badge with its text at {@code textScale} (2 for the enlarged Téracristal value); height grows with it. */
	protected int drawTypeBadge(GuiGraphics g, ElementalType type, float xf, float yf, float textScale) {
		int x = Math.round(xf);
		int y = Math.round(yf);
		String label = upper(type.getDisplayName().getString());
		int w = typeBadgeWidth(type, textScale);
		int h = typeBadgeHeight(textScale);
		int bg = typeColor(type);
		int t = hairline();
		g.fill(x + t, y + t, x + w - t, y + h - t, bg);
		g.fill(x + t, y, x + w - t, y + t, BADGE_BORDER);
		g.fill(x + t, y + h - t, x + w - t, y + h, BADGE_BORDER);
		g.fill(x, y + t, x + t, y + h - t, BADGE_BORDER);
		g.fill(x + w - t, y + t, x + w, y + h - t, BADGE_BORDER);
		float textHeight = 7 * snapTextScale(textScale);
		drawText(g, label, x + 8, y + (h - textHeight) / 2f, textScale, 0xFF000000 | PokemonGuiRendering.readableTextColor(bg), false, 0.5f);
		return w;
	}

	protected int typeBadgeHeight(float textScale) {
		return Math.round(7 * snapTextScale(textScale)) + 12;
	}

	/**
	 * Official type colors (Adrien 2026-10-02: "couleurs officielles") — the
	 * palette of the current games' type icons (Scarlet/Violet, Pokémon HOME),
	 * as used by Bulbapedia's type templates. Cobblemon's own
	 * {@code getPrimaryColor()} only for anything not listed (custom types).
	 */
	private static final Map<String, Integer> OFFICIAL_TYPE_COLORS = Map.ofEntries(
			Map.entry("normal", 0x9FA19F), Map.entry("fire", 0xE62829), Map.entry("water", 0x2980EF),
			Map.entry("electric", 0xFAC000), Map.entry("grass", 0x3FA129), Map.entry("ice", 0x3DCEF3),
			Map.entry("fighting", 0xFF8000), Map.entry("poison", 0x9141CB), Map.entry("ground", 0x915121),
			Map.entry("flying", 0x81B9EF), Map.entry("psychic", 0xEF4179), Map.entry("bug", 0x91A119),
			Map.entry("rock", 0xAFA981), Map.entry("ghost", 0x704170), Map.entry("dragon", 0x5060E1),
			Map.entry("dark", 0x624D4E), Map.entry("steel", 0x60A1B8), Map.entry("fairy", 0xEF70EF),
			Map.entry("stellar", 0x40B5A5));

	protected static int typeColor(ElementalType type) {
		Integer official = OFFICIAL_TYPE_COLORS.get(type.getName().toLowerCase(Locale.ROOT));
		return 0xFF000000 | (official != null ? official : type.getPrimaryColor());
	}

	protected int typeBadgeWidth(ElementalType type, float textScale) {
		return Math.round(textWidth(upper(type.getDisplayName().getString()), textScale, false, 0.5f)) + 16;
	}

	protected void drawGender(GuiGraphics g, PokemonGender gender, float x, float y, float textScale) {
		if (gender == PokemonGender.MALE) {
			drawText(g, "♂", x, y, textScale, MALE, false, 0f);
		} else if (gender == PokemonGender.FEMALE) {
			drawText(g, "♀", x, y, textScale, FEMALE, false, 0f);
		}
	}

	protected void enableCanvasScissor(GuiGraphics g, int x, int y, int w, int h) {
		g.enableScissor(
				Math.round(originX + x * scale), Math.round(originY + y * scale),
				Math.round(originX + (x + w) * scale), Math.round(originY + (y + h) * scale));
	}

	protected void drawCentered(GuiGraphics g, String text, float centerX, float y, float textScale, int color, boolean bold, float spacing) {
		drawText(g, text, centerX - textWidth(text, textScale, bold, spacing) / 2f, y, textScale, color, bold, spacing);
	}

	/**
	 * Font scale actually used for a requested {@code textScale}: snapped so
	 * one font pixel is a whole number of screen pixels (at least one). At a
	 * non-integer ratio, nearest-neighbour sampling drops/duplicates font
	 * columns and small text turns into an unreadable smear (Adrien's PC
	 * capture, 2026-10-02: buttons and the nature +/- text).
	 */
	protected float snapTextScale(float textScale) {
		float ppx = pixelsPerCanvasPx();
		return ppx <= 0 ? textScale : Math.max(1, Math.round(textScale * ppx)) / ppx;
	}

	/** Letter-spacing rounded to whole screen pixels, so every glyph stays on the pixel grid. */
	private float snapSpacing(float spacing) {
		float ppx = pixelsPerCanvasPx();
		return spacing <= 0f || ppx <= 0 ? Math.max(0f, spacing) : Math.round(spacing * ppx) / ppx;
	}

	/** Canvas x → nearest canvas x that lands exactly on a screen pixel. */
	private float snapX(float x) {
		double gui = Minecraft.getInstance().getWindow().getGuiScale();
		return (float) ((Math.round((originX + x * scale) * gui) / gui - originX) / scale);
	}

	private float snapY(float y) {
		double gui = Minecraft.getInstance().getWindow().getGuiScale();
		return (float) ((Math.round((originY + y * scale) * gui) / gui - originY) / scale);
	}

	/** Draws {@code text} with its glyph top at {@code y}, optionally with CSS-like {@code letter-spacing} (canvas px). Pixel-snapped, see {@link #snapTextScale}. */
	protected void drawText(GuiGraphics g, String text, float x, float y, float textScale, int color, boolean bold, float spacing) {
		if (text == null || text.isEmpty() || (color >>> 24) < 8) {
			return;
		}
		float effectiveScale = snapTextScale(textScale);
		float effectiveSpacing = snapSpacing(spacing);
		PoseStack pose = g.pose();
		pose.pushPose();
		pose.translate(snapX(x), snapY(y), 0);
		pose.scale(effectiveScale, effectiveScale, 1f);
		if (effectiveSpacing <= 0f) {
			g.drawString(font, styled(text, bold), 0, 0, color, false);
		} else {
			float cursor = 0f;
			int i = 0;
			while (i < text.length()) {
				int codePoint = text.codePointAt(i);
				String glyph = new String(Character.toChars(codePoint));
				pose.pushPose();
				pose.translate(cursor, 0, 0);
				g.drawString(font, styled(glyph, bold), 0, 0, color, false);
				pose.popPose();
				cursor += font.width(styled(glyph, bold)) + effectiveSpacing / effectiveScale;
				i += Character.charCount(codePoint);
			}
		}
		pose.popPose();
	}

	protected void drawSequence(GuiGraphics g, FormattedCharSequence sequence, float x, float y, int color) {
		float effectiveScale = snapTextScale(1f);
		PoseStack pose = g.pose();
		pose.pushPose();
		pose.translate(snapX(x), snapY(y), 0);
		pose.scale(effectiveScale, effectiveScale, 1f);
		g.drawString(font, sequence, 0, 0, color, false);
		pose.popPose();
	}

	/** Width of a {@link #drawSequence} line, in canvas px. */
	protected float sequenceWidth(FormattedCharSequence sequence) {
		return font.width(sequence) * snapTextScale(1f);
	}

	/** Rendered width in canvas px, letter-spacing included (same snapping as {@link #drawText}). */
	protected float textWidth(String text, float textScale, boolean bold, float spacing) {
		if (text == null || text.isEmpty()) {
			return 0f;
		}
		int glyphs = text.codePointCount(0, text.length());
		// Bold safety margin: some modpack fonts draw bold one font pixel wider per glyph than font.width() reports.
		int boldMargin = bold ? glyphs : 0;
		return (font.width(styled(text, bold)) + boldMargin) * snapTextScale(textScale) + snapSpacing(spacing) * (glyphs - 1);
	}

	/** Truncates with "…" so the text fits in {@code maxWidth} canvas px (no overflowing text). */
	protected String fitText(String text, float maxWidth, float textScale, boolean bold, float spacing) {
		if (text == null || textWidth(text, textScale, bold, spacing) <= maxWidth) {
			return text;
		}
		String ellipsis = "…";
		String result = text;
		while (!result.isEmpty() && textWidth(result + ellipsis, textScale, bold, spacing) > maxWidth) {
			result = result.substring(0, result.length() - 1);
		}
		return result.stripTrailing() + ellipsis;
	}

	protected static MutableComponent styled(String text, boolean bold) {
		MutableComponent component = Component.literal(text);
		return bold ? component.withStyle(ChatFormatting.BOLD) : component;
	}

	protected static String upper(String text) {
		return text == null ? "" : text.toUpperCase(Locale.ROOT);
	}

	protected static String stripPrefix(String message) {
		return message.startsWith("[Phantasmon] ") ? message.substring("[Phantasmon] ".length()) : message;
	}

	protected static int argb(int rgb, float alpha) {
		int a = Math.max(0, Math.min(255, Math.round(alpha * 255)));
		return (a << 24) | (rgb & 0xFFFFFF);
	}

	protected static int withAlpha(int argbColor, float factor) {
		int a = Math.round(((argbColor >>> 24) & 0xFF) * Math.max(0f, Math.min(1f, factor)));
		return (a << 24) | (argbColor & 0xFFFFFF);
	}

	protected static int lerpColor(int from, int to, float t) {
		int r = Math.round(((from >> 16) & 0xFF) + (((to >> 16) & 0xFF) - ((from >> 16) & 0xFF)) * t);
		int gr = Math.round(((from >> 8) & 0xFF) + (((to >> 8) & 0xFF) - ((from >> 8) & 0xFF)) * t);
		int b = Math.round((from & 0xFF) + ((to & 0xFF) - (from & 0xFF)) * t);
		return (r << 16) | (gr << 8) | b;
	}

	// =====================================================================
	// Pokémon data → display (Cobblemon lookups, local data only)
	// =====================================================================

	/** Nickname if set, else Cobblemon's localized species name, else the raw id capitalized. Public: also used for chat summaries. */
	public static String displayName(PokemonDto pokemon) {
		Object nickname = pokemon.data() == null ? null : pokemon.data().get("nickname");
		if (nickname != null && !nickname.toString().isBlank()) {
			return nickname.toString();
		}
		Species species = PokemonSpecies.INSTANCE.getByName(pokemon.species());
		if (species != null) {
			return species.getTranslatedName().getString();
		}
		String id = pokemon.species() == null ? "?" : pokemon.species();
		return id.isEmpty() ? id : id.substring(0, 1).toUpperCase(Locale.ROOT) + id.substring(1);
	}

	protected static ItemStack heldItem(PokemonDto pokemon) {
		Object raw = pokemon.data() == null ? null : pokemon.data().get("heldItem");
		return raw == null ? ItemStack.EMPTY : PokemonGuiRendering.heldItemStack(raw.toString());
	}

	/** {@link AbilityTemplate#getDisplayName()} is a raw translation key, not resolved text. */
	protected static String abilityLabel(String abilityId) {
		if (abilityId == null) {
			return "?";
		}
		AbilityTemplate template = Abilities.get(abilityId);
		return template != null ? Component.translatable(template.getDisplayName()).getString() : abilityId;
	}

	/** Everything a card/slot needs from Cobblemon's local data for one Pokémon, resolved once per draw. */
	protected record Look(List<ElementalType> types, ElementalType teraType, PokemonGender gender) {

		static Look of(PokemonDto pokemon) {
			Species species = PokemonSpecies.INSTANCE.getByName(pokemon.species());
			FormData form = species == null ? null : formOf(species, pokemon.form());
			List<ElementalType> types = new java.util.ArrayList<>();
			ElementalType primary = form != null ? form.getPrimaryType() : species != null ? species.getPrimaryType() : null;
			ElementalType secondary = form != null ? form.getSecondaryType() : species != null ? species.getSecondaryType() : null;
			if (primary != null) {
				types.add(primary);
			}
			if (secondary != null) {
				types.add(secondary);
			}
			Map<String, Object> data = pokemon.data() != null ? pokemon.data() : Map.of();
			Object teraRaw = data.get("teraType");
			// Every Pokémon has an inherent Tera Type (its own primary type) until changed.
			ElementalType tera = teraRaw != null ? safeType(teraRaw.toString()) : primary;
			Float maleRatio = form != null ? Float.valueOf(form.getMaleRatio()) : species != null ? Float.valueOf(species.getMaleRatio()) : null;
			return new Look(types, tera, PokemonGender.resolve(data.get("gender"), maleRatio));
		}

		private static FormData formOf(Species species, String formId) {
			FormData form = PokemonGuiRendering.resolveForm(species, formId);
			return form != null ? form : species.getStandardForm();
		}


		static ElementalType safeType(String typeId) {
			if (typeId == null) {
				return null;
			}
			try {
				return ElementalTypes.INSTANCE.get(typeId.toLowerCase(Locale.ROOT));
			} catch (Exception ex) {
				return null;
			}
		}
	}

	@SuppressWarnings("unchecked")
	protected static Map<String, Object> asMap(Object value) {
		return value instanceof Map ? (Map<String, Object>) value : Map.of();
	}

	@SuppressWarnings("unchecked")
	protected static List<Object> asList(Object value) {
		return value instanceof List ? (List<Object>) value : List.of();
	}

	protected static int asInt(Object value) {
		return value instanceof Number number ? number.intValue() : 0;
	}

	/** Secondary header action next to IMPORTER (same frame, "⇪" glyph): EXPORTER, Showdown text to the clipboard. */
	protected void renderExportButton(GuiGraphics g, int x, int y, int w, int h, boolean hovered) {
		renderPrimaryButtonFrame(g, x, y, w, h, hovered, false);
		String glyph = "⇪";
		String label = upper(Component.translatable("phantasmon.pc.screen.export").getString());
		float glyphWidth = textWidth(glyph, 2f, true, 0f);
		float labelScale = textWidth(label, 2f, true, 1f) + glyphWidth + 8 <= w - 16 ? 2f : 1f;
		float labelWidth = textWidth(label, labelScale, true, 1f);
		float startX = x + (w - glyphWidth - 8 - labelWidth) / 2f;
		drawText(g, glyph, startX, y + 17, 2f, CYAN, true, 0f);
		drawText(g, label, startX + glyphWidth + 8, y + (h - 7 * labelScale) / 2f, labelScale, CYAN, true, 1f);
	}
}
